var searchData=
[
  ['l1',['L1',['https://docs.opencv.org/3.4.1/df/d95/structcvflann_1_1L1.html',1,'cvflann::L1&lt; class &gt;'],['https://docs.opencv.org/3.4.1/d4/d7f/structcv_1_1L1.html',1,'cv::L1&lt; class &gt;']]],
  ['l2',['L2',['https://docs.opencv.org/3.4.1/d9/da3/structcvflann_1_1L2.html',1,'cvflann::L2&lt; class &gt;'],['https://docs.opencv.org/3.4.1/dc/daa/structcv_1_1L2.html',1,'cv::L2&lt; class &gt;']]],
  ['l2_5fsimple',['L2_Simple',['https://docs.opencv.org/3.4.1/da/d59/structcvflann_1_1L2__Simple.html',1,'cvflann']]],
  ['lab2rgb',['Lab2RGB',['https://docs.opencv.org/3.4.1/d0/de5/classcv_1_1cudev_1_1color__cvt__detail_1_1Lab2RGB.html',1,'cv::cudev::color_cvt_detail']]],
  ['lab4_5fto_5fbgr_5ffunc',['Lab4_to_BGR_func',['https://docs.opencv.org/3.4.1/d0/d9b/structcv_1_1cudev_1_1Lab4__to__BGR__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5fbgra_5ffunc',['Lab4_to_BGRA_func',['https://docs.opencv.org/3.4.1/dd/d90/structcv_1_1cudev_1_1Lab4__to__BGRA__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5flbgr_5ffunc',['Lab4_to_LBGR_func',['https://docs.opencv.org/3.4.1/d6/daa/structcv_1_1cudev_1_1Lab4__to__LBGR__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5flbgra_5ffunc',['Lab4_to_LBGRA_func',['https://docs.opencv.org/3.4.1/d5/d42/structcv_1_1cudev_1_1Lab4__to__LBGRA__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5flrgb_5ffunc',['Lab4_to_LRGB_func',['https://docs.opencv.org/3.4.1/d8/d8b/structcv_1_1cudev_1_1Lab4__to__LRGB__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5flrgba_5ffunc',['Lab4_to_LRGBA_func',['https://docs.opencv.org/3.4.1/da/d79/structcv_1_1cudev_1_1Lab4__to__LRGBA__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5frgb_5ffunc',['Lab4_to_RGB_func',['https://docs.opencv.org/3.4.1/d6/d85/structcv_1_1cudev_1_1Lab4__to__RGB__func.html',1,'cv::cudev']]],
  ['lab4_5fto_5frgba_5ffunc',['Lab4_to_RGBA_func',['https://docs.opencv.org/3.4.1/d2/d63/structcv_1_1cudev_1_1Lab4__to__RGBA__func.html',1,'cv::cudev']]],
  ['lab_5fto_5fbgr_5ffunc',['Lab_to_BGR_func',['https://docs.opencv.org/3.4.1/d7/d73/structcv_1_1cudev_1_1Lab__to__BGR__func.html',1,'cv::cudev']]],
  ['lab_5fto_5fbgra_5ffunc',['Lab_to_BGRA_func',['https://docs.opencv.org/3.4.1/d0/dd1/structcv_1_1cudev_1_1Lab__to__BGRA__func.html',1,'cv::cudev']]],
  ['lab_5fto_5flbgr_5ffunc',['Lab_to_LBGR_func',['https://docs.opencv.org/3.4.1/d6/d7e/structcv_1_1cudev_1_1Lab__to__LBGR__func.html',1,'cv::cudev']]],
  ['lab_5fto_5flbgra_5ffunc',['Lab_to_LBGRA_func',['https://docs.opencv.org/3.4.1/df/ddf/structcv_1_1cudev_1_1Lab__to__LBGRA__func.html',1,'cv::cudev']]],
  ['lab_5fto_5flrgb_5ffunc',['Lab_to_LRGB_func',['https://docs.opencv.org/3.4.1/d0/d79/structcv_1_1cudev_1_1Lab__to__LRGB__func.html',1,'cv::cudev']]],
  ['lab_5fto_5flrgba_5ffunc',['Lab_to_LRGBA_func',['https://docs.opencv.org/3.4.1/dc/d4d/structcv_1_1cudev_1_1Lab__to__LRGBA__func.html',1,'cv::cudev']]],
  ['lab_5fto_5frgb_5ffunc',['Lab_to_RGB_func',['https://docs.opencv.org/3.4.1/d4/d08/structcv_1_1cudev_1_1Lab__to__RGB__func.html',1,'cv::cudev']]],
  ['lab_5fto_5frgba_5ffunc',['Lab_to_RGBA_func',['https://docs.opencv.org/3.4.1/df/df8/structcv_1_1cudev_1_1Lab__to__RGBA__func.html',1,'cv::cudev']]],
  ['laplacianptr',['LaplacianPtr',['https://docs.opencv.org/3.4.1/da/d40/structcv_1_1cudev_1_1LaplacianPtr.html',1,'cv::cudev']]],
  ['laplacianptr_3c_201_2c_20srcptr_20_3e',['LaplacianPtr&lt; 1, SrcPtr &gt;',['https://docs.opencv.org/3.4.1/d0/de6/structcv_1_1cudev_1_1LaplacianPtr_3_011_00_01SrcPtr_01_4.html',1,'cv::cudev']]],
  ['laplacianptr_3c_203_2c_20srcptr_20_3e',['LaplacianPtr&lt; 3, SrcPtr &gt;',['https://docs.opencv.org/3.4.1/d4/d89/structcv_1_1cudev_1_1LaplacianPtr_3_013_00_01SrcPtr_01_4.html',1,'cv::cudev']]],
  ['laplacianptrsz',['LaplacianPtrSz',['https://docs.opencv.org/3.4.1/da/dd9/structcv_1_1cudev_1_1LaplacianPtrSz.html',1,'cv::cudev']]],
  ['largertype',['LargerType',['https://docs.opencv.org/3.4.1/d5/d33/structcv_1_1cudev_1_1LargerType.html',1,'cv::cudev']]],
  ['latch',['LATCH',['https://docs.opencv.org/3.4.1/d6/d36/classcv_1_1xfeatures2d_1_1LATCH.html',1,'cv::xfeatures2d']]],
  ['layer',['Layer',['https://docs.opencv.org/3.4.1/d3/d6c/classcv_1_1dnn_1_1Layer.html',1,'cv::dnn']]],
  ['layerfactory',['LayerFactory',['https://docs.opencv.org/3.4.1/d4/d67/classcv_1_1dnn_1_1LayerFactory.html',1,'cv::dnn']]],
  ['layerparams',['LayerParams',['https://docs.opencv.org/3.4.1/db/db6/classcv_1_1dnn_1_1LayerParams.html',1,'cv::dnn']]],
  ['lbgr_5fto_5flab4_5ffunc',['LBGR_to_Lab4_func',['https://docs.opencv.org/3.4.1/d3/d25/structcv_1_1cudev_1_1LBGR__to__Lab4__func.html',1,'cv::cudev']]],
  ['lbgr_5fto_5flab_5ffunc',['LBGR_to_Lab_func',['https://docs.opencv.org/3.4.1/dd/d07/structcv_1_1cudev_1_1LBGR__to__Lab__func.html',1,'cv::cudev']]],
  ['lbgr_5fto_5fluv4_5ffunc',['LBGR_to_Luv4_func',['https://docs.opencv.org/3.4.1/db/d4d/structcv_1_1cudev_1_1LBGR__to__Luv4__func.html',1,'cv::cudev']]],
  ['lbgr_5fto_5fluv_5ffunc',['LBGR_to_Luv_func',['https://docs.opencv.org/3.4.1/d8/d9e/structcv_1_1cudev_1_1LBGR__to__Luv__func.html',1,'cv::cudev']]],
  ['lbgra_5fto_5flab4_5ffunc',['LBGRA_to_Lab4_func',['https://docs.opencv.org/3.4.1/dc/db6/structcv_1_1cudev_1_1LBGRA__to__Lab4__func.html',1,'cv::cudev']]],
  ['lbgra_5fto_5flab_5ffunc',['LBGRA_to_Lab_func',['https://docs.opencv.org/3.4.1/d5/d55/structcv_1_1cudev_1_1LBGRA__to__Lab__func.html',1,'cv::cudev']]],
  ['lbgra_5fto_5fluv4_5ffunc',['LBGRA_to_Luv4_func',['https://docs.opencv.org/3.4.1/df/d4b/structcv_1_1cudev_1_1LBGRA__to__Luv4__func.html',1,'cv::cudev']]],
  ['lbgra_5fto_5fluv_5ffunc',['LBGRA_to_Luv_func',['https://docs.opencv.org/3.4.1/d2/d19/structcv_1_1cudev_1_1LBGRA__to__Luv__func.html',1,'cv::cudev']]],
  ['lbphfacerecognizer',['LBPHFaceRecognizer',['https://docs.opencv.org/3.4.1/df/d25/classcv_1_1face_1_1LBPHFaceRecognizer.html',1,'cv::face']]],
  ['lconv',['lconv',['http://en.cppreference.com/w/cpp/locale/lconv.html',1,'std']]],
  ['lda',['LDA',['https://docs.opencv.org/3.4.1/db/d59/classcv_1_1LDA.html',1,'cv']]],
  ['learningbasedwb',['LearningBasedWB',['https://docs.opencv.org/3.4.1/d4/d3b/classcv_1_1xphoto_1_1LearningBasedWB.html',1,'cv::xphoto']]],
  ['length_5ferror',['length_error',['http://en.cppreference.com/w/cpp/error/length_error.html',1,'std']]],
  ['less',['less',['http://en.cppreference.com/w/cpp/utility/functional/less.html',1,'std::less'],['https://docs.opencv.org/3.4.1/d0/d04/structcv_1_1cudev_1_1less.html',1,'cv::cudev::less&lt; class &gt;']]],
  ['less_5fequal',['less_equal',['http://en.cppreference.com/w/cpp/utility/functional/less_equal.html',1,'std::less_equal'],['https://docs.opencv.org/3.4.1/d1/d03/structcv_1_1cudev_1_1less__equal.html',1,'cv::cudev::less_equal&lt; class &gt;']]],
  ['libmv_5fcameraintrinsicsoptions',['libmv_CameraIntrinsicsOptions',['https://docs.opencv.org/3.4.1/d9/d5a/classcv_1_1sfm_1_1libmv__CameraIntrinsicsOptions.html',1,'cv::sfm']]],
  ['libmv_5freconstructionoptions',['libmv_ReconstructionOptions',['https://docs.opencv.org/3.4.1/d1/d61/classcv_1_1sfm_1_1libmv__ReconstructionOptions.html',1,'cv::sfm']]],
  ['linear_5fcongruential_5fengine',['linear_congruential_engine',['http://en.cppreference.com/w/cpp/numeric/random/linear_congruential_engine.html',1,'std']]],
  ['linearindex',['LinearIndex',['https://docs.opencv.org/3.4.1/d2/d37/classcvflann_1_1LinearIndex.html',1,'cvflann']]],
  ['linearindexparams',['LinearIndexParams',['https://docs.opencv.org/3.4.1/d5/d24/structcvflann_1_1LinearIndexParams.html',1,'cvflann::LinearIndexParams'],['https://docs.opencv.org/3.4.1/da/d5d/structcv_1_1flann_1_1LinearIndexParams.html',1,'cv::flann::LinearIndexParams']]],
  ['linearinterptr',['LinearInterPtr',['https://docs.opencv.org/3.4.1/d7/d8a/structcv_1_1cudev_1_1LinearInterPtr.html',1,'cv::cudev']]],
  ['linearinterptrsz',['LinearInterPtrSz',['https://docs.opencv.org/3.4.1/d9/d2e/structcv_1_1cudev_1_1LinearInterPtrSz.html',1,'cv::cudev']]],
  ['lineiterator',['LineIterator',['https://docs.opencv.org/3.4.1/dc/dd2/classcv_1_1LineIterator.html',1,'cv']]],
  ['linesegmentdetector',['LineSegmentDetector',['https://docs.opencv.org/3.4.1/db/d73/classcv_1_1LineSegmentDetector.html',1,'cv']]],
  ['list',['list',['http://en.cppreference.com/w/cpp/container/list.html',1,'std']]],
  ['locale',['locale',['http://en.cppreference.com/w/cpp/locale/locale.html',1,'std']]],
  ['lock_5fguard',['lock_guard',['http://en.cppreference.com/w/cpp/thread/lock_guard.html',1,'std::lock_guard'],['https://docs.opencv.org/3.4.1/de/d29/classcv_1_1utils_1_1lock__guard.html',1,'cv::utils::lock_guard&lt; class &gt;']]],
  ['log10_5ffunc',['log10_func',['https://docs.opencv.org/3.4.1/d8/da8/structcv_1_1cudev_1_1log10__func.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20double_20_3e',['log10_func&lt; double &gt;',['https://docs.opencv.org/3.4.1/dc/d32/structcv_1_1cudev_1_1log10__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20float_20_3e',['log10_func&lt; float &gt;',['https://docs.opencv.org/3.4.1/d0/d42/structcv_1_1cudev_1_1log10__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20schar_20_3e',['log10_func&lt; schar &gt;',['https://docs.opencv.org/3.4.1/dd/d4b/structcv_1_1cudev_1_1log10__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20short_20_3e',['log10_func&lt; short &gt;',['https://docs.opencv.org/3.4.1/d9/d00/structcv_1_1cudev_1_1log10__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20uchar_20_3e',['log10_func&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/dd/dcc/structcv_1_1cudev_1_1log10__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20uint_20_3e',['log10_func&lt; uint &gt;',['https://docs.opencv.org/3.4.1/df/d6e/structcv_1_1cudev_1_1log10__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['log10_5ffunc_3c_20ushort_20_3e',['log10_func&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/d0/df1/structcv_1_1cudev_1_1log10__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['log2',['Log2',['https://docs.opencv.org/3.4.1/d5/da6/structcv_1_1cudev_1_1Log2.html',1,'cv::cudev']]],
  ['log2_3c_20n_2c_200_2c_20count_20_3e',['Log2&lt; N, 0, COUNT &gt;',['https://docs.opencv.org/3.4.1/d5/d16/structcv_1_1cudev_1_1Log2_3_01N_00_010_00_01COUNT_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc',['log2_func',['https://docs.opencv.org/3.4.1/d9/d23/structcv_1_1cudev_1_1log2__func.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20double_20_3e',['log2_func&lt; double &gt;',['https://docs.opencv.org/3.4.1/dc/d17/structcv_1_1cudev_1_1log2__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20float_20_3e',['log2_func&lt; float &gt;',['https://docs.opencv.org/3.4.1/db/dba/structcv_1_1cudev_1_1log2__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20schar_20_3e',['log2_func&lt; schar &gt;',['https://docs.opencv.org/3.4.1/d6/ded/structcv_1_1cudev_1_1log2__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20short_20_3e',['log2_func&lt; short &gt;',['https://docs.opencv.org/3.4.1/d6/d0b/structcv_1_1cudev_1_1log2__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20uchar_20_3e',['log2_func&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/d6/d41/structcv_1_1cudev_1_1log2__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20uint_20_3e',['log2_func&lt; uint &gt;',['https://docs.opencv.org/3.4.1/df/d69/structcv_1_1cudev_1_1log2__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['log2_5ffunc_3c_20ushort_20_3e',['log2_func&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/d0/dda/structcv_1_1cudev_1_1log2__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc',['log_func',['https://docs.opencv.org/3.4.1/dc/d41/structcv_1_1cudev_1_1log__func.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20double_20_3e',['log_func&lt; double &gt;',['https://docs.opencv.org/3.4.1/dd/dad/structcv_1_1cudev_1_1log__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20float_20_3e',['log_func&lt; float &gt;',['https://docs.opencv.org/3.4.1/d2/d85/structcv_1_1cudev_1_1log__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20schar_20_3e',['log_func&lt; schar &gt;',['https://docs.opencv.org/3.4.1/d2/de1/structcv_1_1cudev_1_1log__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20short_20_3e',['log_func&lt; short &gt;',['https://docs.opencv.org/3.4.1/d0/d19/structcv_1_1cudev_1_1log__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20uchar_20_3e',['log_func&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/d3/db5/structcv_1_1cudev_1_1log__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20uint_20_3e',['log_func&lt; uint &gt;',['https://docs.opencv.org/3.4.1/d0/dee/structcv_1_1cudev_1_1log__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['log_5ffunc_3c_20ushort_20_3e',['log_func&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/d5/d0c/structcv_1_1cudev_1_1log__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['logger',['Logger',['https://docs.opencv.org/3.4.1/d1/d50/classcvflann_1_1Logger.html',1,'cvflann']]],
  ['logic_5ferror',['logic_error',['http://en.cppreference.com/w/cpp/error/logic_error.html',1,'std']]],
  ['logical_5fand',['logical_and',['http://en.cppreference.com/w/cpp/utility/functional/logical_and.html',1,'std::logical_and'],['https://docs.opencv.org/3.4.1/d7/de9/structcv_1_1cudev_1_1logical__and.html',1,'cv::cudev::logical_and&lt; class &gt;']]],
  ['logical_5fnot',['logical_not',['http://en.cppreference.com/w/cpp/utility/functional/logical_not.html',1,'std::logical_not'],['https://docs.opencv.org/3.4.1/d4/d01/structcv_1_1cudev_1_1logical__not.html',1,'cv::cudev::logical_not&lt; class &gt;']]],
  ['logical_5for',['logical_or',['http://en.cppreference.com/w/cpp/utility/functional/logical_or.html',1,'std::logical_or'],['https://docs.opencv.org/3.4.1/d3/db2/structcv_1_1cudev_1_1logical__or.html',1,'cv::cudev::logical_or&lt; class &gt;']]],
  ['logisticregression',['LogisticRegression',['https://docs.opencv.org/3.4.1/d6/df9/classcv_1_1ml_1_1LogisticRegression.html',1,'cv::ml']]],
  ['lognormal_5fdistribution',['lognormal_distribution',['http://en.cppreference.com/w/cpp/numeric/random/lognormal_distribution.html',1,'std']]],
  ['logtomatlab',['LogToMATLAB',['../class_log_to_m_a_t_l_a_b.html',1,'']]],
  ['logtostdout',['LogToStdout',['https://docs.opencv.org/3.4.1/d5/de0/classcv_1_1videostab_1_1LogToStdout.html',1,'cv::videostab']]],
  ['lookuptable',['LookUpTable',['https://docs.opencv.org/3.4.1/df/d29/classcv_1_1cuda_1_1LookUpTable.html',1,'cv::cuda']]],
  ['lpmotionstabilizer',['LpMotionStabilizer',['https://docs.opencv.org/3.4.1/d3/d59/classcv_1_1videostab_1_1LpMotionStabilizer.html',1,'cv::videostab']]],
  ['lrgb_5fto_5flab4_5ffunc',['LRGB_to_Lab4_func',['https://docs.opencv.org/3.4.1/db/d2b/structcv_1_1cudev_1_1LRGB__to__Lab4__func.html',1,'cv::cudev']]],
  ['lrgb_5fto_5flab_5ffunc',['LRGB_to_Lab_func',['https://docs.opencv.org/3.4.1/d6/db7/structcv_1_1cudev_1_1LRGB__to__Lab__func.html',1,'cv::cudev']]],
  ['lrgb_5fto_5fluv4_5ffunc',['LRGB_to_Luv4_func',['https://docs.opencv.org/3.4.1/d7/dc8/structcv_1_1cudev_1_1LRGB__to__Luv4__func.html',1,'cv::cudev']]],
  ['lrgb_5fto_5fluv_5ffunc',['LRGB_to_Luv_func',['https://docs.opencv.org/3.4.1/d7/d62/structcv_1_1cudev_1_1LRGB__to__Luv__func.html',1,'cv::cudev']]],
  ['lrgba_5fto_5flab4_5ffunc',['LRGBA_to_Lab4_func',['https://docs.opencv.org/3.4.1/de/d7f/structcv_1_1cudev_1_1LRGBA__to__Lab4__func.html',1,'cv::cudev']]],
  ['lrgba_5fto_5flab_5ffunc',['LRGBA_to_Lab_func',['https://docs.opencv.org/3.4.1/dc/d12/structcv_1_1cudev_1_1LRGBA__to__Lab__func.html',1,'cv::cudev']]],
  ['lrgba_5fto_5fluv4_5ffunc',['LRGBA_to_Luv4_func',['https://docs.opencv.org/3.4.1/dd/dea/structcv_1_1cudev_1_1LRGBA__to__Luv4__func.html',1,'cv::cudev']]],
  ['lrgba_5fto_5fluv_5ffunc',['LRGBA_to_Luv_func',['https://docs.opencv.org/3.4.1/d2/d19/structcv_1_1cudev_1_1LRGBA__to__Luv__func.html',1,'cv::cudev']]],
  ['lrnlayer',['LRNLayer',['https://docs.opencv.org/3.4.1/d8/d8d/classcv_1_1dnn_1_1LRNLayer.html',1,'cv::dnn']]],
  ['lsddetector',['LSDDetector',['https://docs.opencv.org/3.4.1/d1/dbd/classcv_1_1line__descriptor_1_1LSDDetector.html',1,'cv::line_descriptor']]],
  ['lshindex',['LshIndex',['https://docs.opencv.org/3.4.1/d5/d34/classcvflann_1_1LshIndex.html',1,'cvflann']]],
  ['lshindexparams',['LshIndexParams',['https://docs.opencv.org/3.4.1/d5/ddf/structcvflann_1_1LshIndexParams.html',1,'cvflann::LshIndexParams'],['https://docs.opencv.org/3.4.1/d5/dff/structcv_1_1flann_1_1LshIndexParams.html',1,'cv::flann::LshIndexParams']]],
  ['lshstats',['LshStats',['https://docs.opencv.org/3.4.1/d5/d3e/structcvflann_1_1lsh_1_1LshStats.html',1,'cvflann::lsh']]],
  ['lshtable',['LshTable',['https://docs.opencv.org/3.4.1/d4/d86/classcvflann_1_1lsh_1_1LshTable.html',1,'cvflann::lsh']]],
  ['lstmlayer',['LSTMLayer',['https://docs.opencv.org/3.4.1/db/d3e/classcv_1_1dnn_1_1LSTMLayer.html',1,'cv::dnn']]],
  ['lucid',['LUCID',['https://docs.opencv.org/3.4.1/d4/d86/classcv_1_1xfeatures2d_1_1LUCID.html',1,'cv::xfeatures2d']]],
  ['lutptr',['LutPtr',['https://docs.opencv.org/3.4.1/df/daa/structcv_1_1cudev_1_1LutPtr.html',1,'cv::cudev']]],
  ['lutptrsz',['LutPtrSz',['https://docs.opencv.org/3.4.1/d5/d22/structcv_1_1cudev_1_1LutPtrSz.html',1,'cv::cudev']]],
  ['luv2rgb',['Luv2RGB',['https://docs.opencv.org/3.4.1/d6/d2a/classcv_1_1cudev_1_1color__cvt__detail_1_1Luv2RGB.html',1,'cv::cudev::color_cvt_detail']]],
  ['luv4_5fto_5fbgr_5ffunc',['Luv4_to_BGR_func',['https://docs.opencv.org/3.4.1/d5/d34/structcv_1_1cudev_1_1Luv4__to__BGR__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5fbgra_5ffunc',['Luv4_to_BGRA_func',['https://docs.opencv.org/3.4.1/d4/d0b/structcv_1_1cudev_1_1Luv4__to__BGRA__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5flbgr_5ffunc',['Luv4_to_LBGR_func',['https://docs.opencv.org/3.4.1/d6/d9a/structcv_1_1cudev_1_1Luv4__to__LBGR__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5flbgra_5ffunc',['Luv4_to_LBGRA_func',['https://docs.opencv.org/3.4.1/df/d46/structcv_1_1cudev_1_1Luv4__to__LBGRA__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5flrgb_5ffunc',['Luv4_to_LRGB_func',['https://docs.opencv.org/3.4.1/d8/db0/structcv_1_1cudev_1_1Luv4__to__LRGB__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5flrgba_5ffunc',['Luv4_to_LRGBA_func',['https://docs.opencv.org/3.4.1/d2/dc0/structcv_1_1cudev_1_1Luv4__to__LRGBA__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5frgb_5ffunc',['Luv4_to_RGB_func',['https://docs.opencv.org/3.4.1/de/d9f/structcv_1_1cudev_1_1Luv4__to__RGB__func.html',1,'cv::cudev']]],
  ['luv4_5fto_5frgba_5ffunc',['Luv4_to_RGBA_func',['https://docs.opencv.org/3.4.1/d2/dda/structcv_1_1cudev_1_1Luv4__to__RGBA__func.html',1,'cv::cudev']]],
  ['luv_5fto_5fbgr_5ffunc',['Luv_to_BGR_func',['https://docs.opencv.org/3.4.1/d2/da9/structcv_1_1cudev_1_1Luv__to__BGR__func.html',1,'cv::cudev']]],
  ['luv_5fto_5fbgra_5ffunc',['Luv_to_BGRA_func',['https://docs.opencv.org/3.4.1/df/d49/structcv_1_1cudev_1_1Luv__to__BGRA__func.html',1,'cv::cudev']]],
  ['luv_5fto_5flbgr_5ffunc',['Luv_to_LBGR_func',['https://docs.opencv.org/3.4.1/d3/dfb/structcv_1_1cudev_1_1Luv__to__LBGR__func.html',1,'cv::cudev']]],
  ['luv_5fto_5flbgra_5ffunc',['Luv_to_LBGRA_func',['https://docs.opencv.org/3.4.1/d0/da4/structcv_1_1cudev_1_1Luv__to__LBGRA__func.html',1,'cv::cudev']]],
  ['luv_5fto_5flrgb_5ffunc',['Luv_to_LRGB_func',['https://docs.opencv.org/3.4.1/d7/d11/structcv_1_1cudev_1_1Luv__to__LRGB__func.html',1,'cv::cudev']]],
  ['luv_5fto_5flrgba_5ffunc',['Luv_to_LRGBA_func',['https://docs.opencv.org/3.4.1/d0/d32/structcv_1_1cudev_1_1Luv__to__LRGBA__func.html',1,'cv::cudev']]],
  ['luv_5fto_5frgb_5ffunc',['Luv_to_RGB_func',['https://docs.opencv.org/3.4.1/d4/d45/structcv_1_1cudev_1_1Luv__to__RGB__func.html',1,'cv::cudev']]],
  ['luv_5fto_5frgba_5ffunc',['Luv_to_RGBA_func',['https://docs.opencv.org/3.4.1/d8/d1e/structcv_1_1cudev_1_1Luv__to__RGBA__func.html',1,'cv::cudev']]]
];
