var searchData=
[
  ['daisy',['DAISY',['https://docs.opencv.org/3.4.1/d9/d37/classcv_1_1xfeatures2d_1_1DAISY.html',1,'cv::xfeatures2d']]],
  ['data',['Data',['https://docs.opencv.org/3.4.1/de/d4f/structcv_1_1face_1_1FacemarkAAM_1_1Data.html',1,'cv::face::FacemarkAAM']]],
  ['datadepth',['DataDepth',['https://docs.opencv.org/3.4.1/d7/d0e/classcv_1_1DataDepth.html',1,'cv']]],
  ['dataset',['Dataset',['https://docs.opencv.org/3.4.1/d9/d2e/classcv_1_1datasets_1_1Dataset.html',1,'cv::datasets']]],
  ['datatype',['Datatype',['https://docs.opencv.org/3.4.1/d4/dbd/structcvflann_1_1Datatype.html',1,'cvflann::Datatype&lt; class &gt;'],['https://docs.opencv.org/3.4.1/d0/d3a/classcv_1_1DataType.html',1,'cv::DataType&lt; class &gt;']]],
  ['datatype_3c_20char_20_3e',['Datatype&lt; char &gt;',['https://docs.opencv.org/3.4.1/d3/df4/structcvflann_1_1Datatype_3_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20double_20_3e',['Datatype&lt; double &gt;',['https://docs.opencv.org/3.4.1/d2/d8d/structcvflann_1_1Datatype_3_01double_01_4.html',1,'cvflann']]],
  ['datatype_3c_20float_20_3e',['Datatype&lt; float &gt;',['https://docs.opencv.org/3.4.1/dd/d42/structcvflann_1_1Datatype_3_01float_01_4.html',1,'cvflann']]],
  ['datatype_3c_20short_20_3e',['Datatype&lt; short &gt;',['https://docs.opencv.org/3.4.1/db/de5/structcvflann_1_1Datatype_3_01short_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20char_20_3e',['Datatype&lt; unsigned char &gt;',['https://docs.opencv.org/3.4.1/d3/dea/structcvflann_1_1Datatype_3_01unsigned_01char_01_4.html',1,'cvflann']]],
  ['datatype_3c_20unsigned_20short_20_3e',['Datatype&lt; unsigned short &gt;',['https://docs.opencv.org/3.4.1/dc/dbe/structcvflann_1_1Datatype_3_01unsigned_01short_01_4.html',1,'cvflann']]],
  ['dct2d',['DCT2D',['https://docs.opencv.org/3.4.1/d5/d57/structcv_1_1hal_1_1DCT2D.html',1,'cv::hal']]],
  ['deblurerbase',['DeblurerBase',['https://docs.opencv.org/3.4.1/dd/d05/classcv_1_1videostab_1_1DeblurerBase.html',1,'cv::videostab']]],
  ['deca',['deca',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['decay',['decay',['http://en.cppreference.com/w/cpp/types/decay.html',1,'std']]],
  ['deci',['deci',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['deconvolutionlayer',['DeconvolutionLayer',['https://docs.opencv.org/3.4.1/dd/d77/classcv_1_1dnn_1_1DeconvolutionLayer.html',1,'cv::dnn']]],
  ['default_5fdelete',['default_delete',['http://en.cppreference.com/w/cpp/memory/default_delete.html',1,'std']]],
  ['default_5frandom_5fengine',['default_random_engine',['http://en.cppreference.com/w/cpp/numeric/random.html',1,'std']]],
  ['defaultcopypolicy',['DefaultCopyPolicy',['https://docs.opencv.org/3.4.1/d8/dc2/structcv_1_1cudev_1_1DefaultCopyPolicy.html',1,'cv::cudev']]],
  ['defaultglobreducepolicy',['DefaultGlobReducePolicy',['https://docs.opencv.org/3.4.1/d2/d04/structcv_1_1cudev_1_1DefaultGlobReducePolicy.html',1,'cv::cudev']]],
  ['defaulthistogrampolicy',['DefaultHistogramPolicy',['https://docs.opencv.org/3.4.1/d4/d2b/structcv_1_1cudev_1_1DefaultHistogramPolicy.html',1,'cv::cudev']]],
  ['defaultreducetovecpolicy',['DefaultReduceToVecPolicy',['https://docs.opencv.org/3.4.1/d3/dd7/structcv_1_1cudev_1_1DefaultReduceToVecPolicy.html',1,'cv::cudev']]],
  ['defaultsplitmergepolicy',['DefaultSplitMergePolicy',['https://docs.opencv.org/3.4.1/d9/d3a/structcv_1_1cudev_1_1DefaultSplitMergePolicy.html',1,'cv::cudev']]],
  ['defaulttraits',['DefaultTraits',['https://docs.opencv.org/3.4.1/d7/db5/classmatlab_1_1DefaultTraits.html',1,'matlab']]],
  ['defaulttransformpolicy',['DefaultTransformPolicy',['https://docs.opencv.org/3.4.1/db/db3/structcv_1_1cudev_1_1DefaultTransformPolicy.html',1,'cv::cudev']]],
  ['defaulttransposepolicy',['DefaultTransposePolicy',['https://docs.opencv.org/3.4.1/dd/d44/structcv_1_1cudev_1_1DefaultTransposePolicy.html',1,'cv::cudev']]],
  ['defer_5flock_5ft',['defer_lock_t',['http://en.cppreference.com/w/cpp/thread/lock_tag_t.html',1,'std']]],
  ['denseopticalflow',['DenseOpticalFlow',['https://docs.opencv.org/3.4.1/df/dde/classcv_1_1DenseOpticalFlow.html',1,'cv::DenseOpticalFlow'],['https://docs.opencv.org/3.4.1/d6/d4a/classcv_1_1cuda_1_1DenseOpticalFlow.html',1,'cv::cuda::DenseOpticalFlow']]],
  ['denseopticalflowext',['DenseOpticalFlowExt',['https://docs.opencv.org/3.4.1/d1/d21/classcv_1_1superres_1_1DenseOpticalFlowExt.html',1,'cv::superres']]],
  ['densepyrlkopticalflow',['DensePyrLKOpticalFlow',['https://docs.opencv.org/3.4.1/d0/da4/classcv_1_1cuda_1_1DensePyrLKOpticalFlow.html',1,'cv::cuda']]],
  ['depthcleaner',['DepthCleaner',['https://docs.opencv.org/3.4.1/d9/d5e/classcv_1_1rgbd_1_1DepthCleaner.html',1,'cv::rgbd']]],
  ['depthnormal',['DepthNormal',['https://docs.opencv.org/3.4.1/d7/d47/classcv_1_1linemod_1_1DepthNormal.html',1,'cv::linemod']]],
  ['deque',['deque',['http://en.cppreference.com/w/cpp/container/deque.html',1,'std']]],
  ['deque_3c_20std_3a_3apair_3c_20uint64_5ft_2c_20uint32_5ft_20_3e_20_3e',['deque&lt; std::pair&lt; uint64_t, uint32_t &gt; &gt;',['http://en.cppreference.com/w/cpp/container/deque.html',1,'std']]],
  ['derivxptr',['DerivXPtr',['https://docs.opencv.org/3.4.1/df/d8b/structcv_1_1cudev_1_1DerivXPtr.html',1,'cv::cudev']]],
  ['derivxptrsz',['DerivXPtrSz',['https://docs.opencv.org/3.4.1/db/d58/structcv_1_1cudev_1_1DerivXPtrSz.html',1,'cv::cudev']]],
  ['derivyptr',['DerivYPtr',['https://docs.opencv.org/3.4.1/dc/d51/structcv_1_1cudev_1_1DerivYPtr.html',1,'cv::cudev']]],
  ['derivyptrsz',['DerivYPtrSz',['https://docs.opencv.org/3.4.1/d2/dfc/structcv_1_1cudev_1_1DerivYPtrSz.html',1,'cv::cudev']]],
  ['descriptorcollection',['DescriptorCollection',['https://docs.opencv.org/3.4.1/d4/dac/classcv_1_1DescriptorMatcher_1_1DescriptorCollection.html',1,'cv::DescriptorMatcher']]],
  ['descriptorextractor',['descriptorExtractor',['https://docs.opencv.org/3.4.1/d7/d8d/classcv_1_1cnn__3dobj_1_1descriptorExtractor.html',1,'cv::cnn_3dobj']]],
  ['descriptormatcher',['DescriptorMatcher',['https://docs.opencv.org/3.4.1/dd/dc5/classcv_1_1cuda_1_1DescriptorMatcher.html',1,'cv::cuda::DescriptorMatcher'],['https://docs.opencv.org/3.4.1/db/d39/classcv_1_1DescriptorMatcher.html',1,'cv::DescriptorMatcher']]],
  ['detectionoutputlayer',['DetectionOutputLayer',['https://docs.opencv.org/3.4.1/da/dbd/classcv_1_1dnn_1_1DetectionOutputLayer.html',1,'cv::dnn']]],
  ['detectionroi',['DetectionROI',['https://docs.opencv.org/3.4.1/d3/d34/structcv_1_1DetectionROI.html',1,'cv']]],
  ['detector',['Detector',['https://docs.opencv.org/3.4.1/de/db6/classcv_1_1Detector.html',1,'cv::Detector'],['https://docs.opencv.org/3.4.1/d7/d07/classcv_1_1linemod_1_1Detector.html',1,'cv::linemod::Detector']]],
  ['detectorparameters',['DetectorParameters',['https://docs.opencv.org/3.4.1/d1/dcd/structcv_1_1aruco_1_1DetectorParameters.html',1,'cv::aruco']]],
  ['device',['Device',['https://docs.opencv.org/3.4.1/d7/d9f/classcv_1_1ocl_1_1Device.html',1,'cv::ocl']]],
  ['deviceinfo',['DeviceInfo',['https://docs.opencv.org/3.4.1/d7/d7c/classcv_1_1cuda_1_1DeviceInfo.html',1,'cv::cuda']]],
  ['dft',['DFT',['https://docs.opencv.org/3.4.1/dc/de5/classcv_1_1cuda_1_1DFT.html',1,'cv::cuda']]],
  ['dft1d',['DFT1D',['https://docs.opencv.org/3.4.1/d8/d03/structcv_1_1hal_1_1DFT1D.html',1,'cv::hal']]],
  ['dft2d',['DFT2D',['https://docs.opencv.org/3.4.1/d6/d77/structcv_1_1hal_1_1DFT2D.html',1,'cv::hal']]],
  ['dict',['Dict',['https://docs.opencv.org/3.4.1/d9/d2b/classcv_1_1dnn_1_1Dict.html',1,'cv::dnn']]],
  ['dictionary',['Dictionary',['https://docs.opencv.org/3.4.1/d5/d0b/classcv_1_1aruco_1_1Dictionary.html',1,'cv::aruco']]],
  ['dictvalue',['DictValue',['https://docs.opencv.org/3.4.1/d4/db3/structcv_1_1dnn_1_1DictValue.html',1,'cv::dnn']]],
  ['direction_5ffunc',['direction_func',['https://docs.opencv.org/3.4.1/d3/d97/structcv_1_1cudev_1_1direction__func.html',1,'cv::cudev']]],
  ['disableif',['DisableIf',['https://docs.opencv.org/3.4.1/df/d27/structcv_1_1cudev_1_1DisableIf.html',1,'cv::cudev']]],
  ['disableif_3c_20false_2c_20t_20_3e',['DisableIf&lt; false, T &gt;',['https://docs.opencv.org/3.4.1/d5/d19/structcv_1_1cudev_1_1DisableIf_3_01false_00_01T_01_4.html',1,'cv::cudev']]],
  ['discard_5fblock_5fengine',['discard_block_engine',['http://en.cppreference.com/w/cpp/numeric/random/discard_block_engine.html',1,'std']]],
  ['discrete_5fdistribution',['discrete_distribution',['http://en.cppreference.com/w/cpp/numeric/random/discrete_distribution.html',1,'std']]],
  ['disjointsets',['DisjointSets',['https://docs.opencv.org/3.4.1/dc/d3e/classcv_1_1detail_1_1DisjointSets.html',1,'cv::detail']]],
  ['disopticalflow',['DISOpticalFlow',['https://docs.opencv.org/3.4.1/da/d06/classcv_1_1optflow_1_1DISOpticalFlow.html',1,'cv::optflow']]],
  ['disparitybilateralfilter',['DisparityBilateralFilter',['https://docs.opencv.org/3.4.1/d8/d4f/classcv_1_1cuda_1_1DisparityBilateralFilter.html',1,'cv::cuda']]],
  ['disparityfilter',['DisparityFilter',['https://docs.opencv.org/3.4.1/db/d72/classcv_1_1ximgproc_1_1DisparityFilter.html',1,'cv::ximgproc']]],
  ['disparitywlsfilter',['DisparityWLSFilter',['https://docs.opencv.org/3.4.1/d9/d51/classcv_1_1ximgproc_1_1DisparityWLSFilter.html',1,'cv::ximgproc']]],
  ['distindex',['DistIndex',['https://docs.opencv.org/3.4.1/d0/d28/structcvflann_1_1UniqueResultSet_1_1DistIndex.html',1,'cvflann::UniqueResultSet']]],
  ['divides',['divides',['https://docs.opencv.org/3.4.1/de/d2a/structcv_1_1cudev_1_1divides.html',1,'cv::cudev::divides&lt; class &gt;'],['http://en.cppreference.com/w/cpp/utility/functional/divides.html',1,'std::divides']]],
  ['dmatch',['DMatch',['https://docs.opencv.org/3.4.1/d4/de0/classcv_1_1DMatch.html',1,'cv']]],
  ['domain_5ferror',['domain_error',['http://en.cppreference.com/w/cpp/error/domain_error.html',1,'std']]],
  ['downhillsolver',['DownhillSolver',['https://docs.opencv.org/3.4.1/d4/d43/classcv_1_1DownhillSolver.html',1,'cv']]],
  ['dpmdetector',['DPMDetector',['https://docs.opencv.org/3.4.1/df/dba/classcv_1_1dpm_1_1DPMDetector.html',1,'cv::dpm']]],
  ['dpseamfinder',['DpSeamFinder',['https://docs.opencv.org/3.4.1/d0/dd5/classcv_1_1detail_1_1DpSeamFinder.html',1,'cv::detail']]],
  ['drawlinesmatchesflags',['DrawLinesMatchesFlags',['https://docs.opencv.org/3.4.1/d8/d6f/structcv_1_1line__descriptor_1_1DrawLinesMatchesFlags.html',1,'cv::line_descriptor']]],
  ['drawmatchesflags',['DrawMatchesFlags',['https://docs.opencv.org/3.4.1/de/d30/structcv_1_1DrawMatchesFlags.html',1,'cv']]],
  ['dtfilter',['DTFilter',['https://docs.opencv.org/3.4.1/d3/d9d/classcv_1_1ximgproc_1_1DTFilter.html',1,'cv::ximgproc']]],
  ['dtrees',['DTrees',['https://docs.opencv.org/3.4.1/d8/d89/classcv_1_1ml_1_1DTrees.html',1,'cv::ml']]],
  ['dualtvl1opticalflow',['DualTVL1OpticalFlow',['https://docs.opencv.org/3.4.1/d6/db1/classcv_1_1superres_1_1DualTVL1OpticalFlow.html',1,'cv::superres::DualTVL1OpticalFlow'],['https://docs.opencv.org/3.4.1/dc/d47/classcv_1_1DualTVL1OpticalFlow.html',1,'cv::DualTVL1OpticalFlow']]],
  ['duration',['duration',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['duration_5fvalues',['duration_values',['http://en.cppreference.com/w/cpp/chrono/duration_values.html',1,'std::chrono']]],
  ['dynamicbitset',['DynamicBitset',['https://docs.opencv.org/3.4.1/d1/d73/classcvflann_1_1DynamicBitset.html',1,'cvflann']]],
  ['dynamicsharedmem',['DynamicSharedMem',['https://docs.opencv.org/3.4.1/d3/d2b/structcv_1_1cudev_1_1DynamicSharedMem.html',1,'cv::cudev']]],
  ['dynamicsharedmem_3c_20double_20_3e',['DynamicSharedMem&lt; double &gt;',['https://docs.opencv.org/3.4.1/db/d28/structcv_1_1cudev_1_1DynamicSharedMem_3_01double_01_4.html',1,'cv::cudev']]],
  ['dynarray',['dynarray',['http://en.cppreference.com/w/cpp/container/dynarray.html',1,'std']]]
];
