var searchData=
[
  ['u16streampos',['u16streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u16string',['u16string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['u32streampos',['u32streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u32string',['u32string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['uint16_5ft',['uint16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint32_5ft',['uint32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint64_5ft',['uint64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint8_5ft',['uint8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast16_5ft',['uint_fast16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast32_5ft',['uint_fast32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast64_5ft',['uint_fast64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast8_5ft',['uint_fast8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast16_5ft',['uint_least16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast32_5ft',['uint_least32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast64_5ft',['uint_least64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast8_5ft',['uint_least8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintmax_5ft',['uintmax_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintptr_5ft',['uintptr_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['ukfsystemmodel',['UkfSystemModel',['https://docs.opencv.org/3.4.1/da/d2b/classcv_1_1tracking_1_1UkfSystemModel.html',1,'cv::tracking']]],
  ['umat',['UMat',['https://docs.opencv.org/3.4.1/d7/d45/classcv_1_1UMat.html',1,'cv']]],
  ['umatdata',['UMatData',['https://docs.opencv.org/3.4.1/db/d58/structcv_1_1UMatData.html',1,'cv']]],
  ['unary_5ffunction',['unary_function',['http://en.cppreference.com/w/cpp/utility/functional/unary_function.html',1,'std::unary_function'],['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'cv::cudev::unary_function&lt; _Arg, _Result &gt;']]],
  ['unary_5ffunction_3c_20double_2c_20double_20_3e',['unary_function&lt; double, double &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20float_2c_20float_20_3e',['unary_function&lt; float, float &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20float_2c_20short_20_3e',['unary_function&lt; float, short &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20int_2c_20float_20_3e',['unary_function&lt; int, float &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20int_2c_20int_20_3e',['unary_function&lt; int, int &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20op_3a_3afirst_5fargument_5ftype_2c_20op_3a_3aresult_5ftype_20_3e',['unary_function&lt; Op::first_argument_type, Op::result_type &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20op_3a_3asecond_5fargument_5ftype_2c_20op_3a_3aresult_5ftype_20_3e',['unary_function&lt; Op::second_argument_type, Op::result_type &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20predicate_3a_3aargument_5ftype_2c_20predicate_3a_3aresult_5ftype_20_3e',['unary_function&lt; Predicate::argument_type, Predicate::result_type &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20schar_2c_20float_20_3e',['unary_function&lt; schar, float &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20schar_2c_20schar_20_3e',['unary_function&lt; schar, schar &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20short_2c_20float_20_3e',['unary_function&lt; short, float &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20short_2c_20short_20_3e',['unary_function&lt; short, short &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20t_2c_20d_20_3e',['unary_function&lt; T, D &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20t_2c_20functional_5fdetail_3a_3afloattype_3c_20t_20_3e_3a_3atype_20_3e',['unary_function&lt; T, functional_detail::FloatType&lt; T &gt;::type &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20t_2c_20makevec_3c_20uchar_2c_20vectraits_3c_20t_20_3e_3a_3acn_20_3e_3a_3atype_20_3e',['unary_function&lt; T, MakeVec&lt; uchar, VecTraits&lt; T &gt;::cn &gt;::type &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20t_2c_20t_20_3e',['unary_function&lt; T, T &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20uchar_2c_20float_20_3e',['unary_function&lt; uchar, float &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20uchar_2c_20uchar_20_3e',['unary_function&lt; uchar, uchar &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20uint_2c_20float_20_3e',['unary_function&lt; uint, float &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20uint_2c_20uint_20_3e',['unary_function&lt; uint, uint &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20ushort_2c_20float_20_3e',['unary_function&lt; ushort, float &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5ffunction_3c_20ushort_2c_20ushort_20_3e',['unary_function&lt; ushort, ushort &gt;',['https://docs.opencv.org/3.4.1/df/d11/structcv_1_1cudev_1_1unary__function.html',1,'']]],
  ['unary_5fnegate',['unary_negate',['http://en.cppreference.com/w/cpp/utility/functional/unary_negate.html',1,'std']]],
  ['unarynegate',['UnaryNegate',['https://docs.opencv.org/3.4.1/d2/d83/structcv_1_1cudev_1_1UnaryNegate.html',1,'cv::cudev']]],
  ['unarytransformptr',['UnaryTransformPtr',['https://docs.opencv.org/3.4.1/dd/d01/structcv_1_1cudev_1_1UnaryTransformPtr.html',1,'cv::cudev']]],
  ['unarytransformptrsz',['UnaryTransformPtrSz',['https://docs.opencv.org/3.4.1/d0/db7/structcv_1_1cudev_1_1UnaryTransformPtrSz.html',1,'cv::cudev']]],
  ['unarytupleadapter',['UnaryTupleAdapter',['https://docs.opencv.org/3.4.1/d4/d57/structcv_1_1cudev_1_1UnaryTupleAdapter.html',1,'cv::cudev']]],
  ['underflow_5ferror',['underflow_error',['http://en.cppreference.com/w/cpp/error/underflow_error.html',1,'std']]],
  ['underlying_5ftype',['underlying_type',['http://en.cppreference.com/w/cpp/types/underlying_type.html',1,'std']]],
  ['unexpected_5fhandler',['unexpected_handler',['http://en.cppreference.com/w/cpp/error/unexpected_handler.html',1,'std']]],
  ['uniform_5fint_5fdistribution',['uniform_int_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution.html',1,'std']]],
  ['uniform_5freal_5fdistribution',['uniform_real_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution.html',1,'std']]],
  ['unique_5flock',['unique_lock',['http://en.cppreference.com/w/cpp/thread/unique_lock.html',1,'std']]],
  ['unique_5fptr',['unique_ptr',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['uniquerandom',['UniqueRandom',['https://docs.opencv.org/3.4.1/d9/de3/classcvflann_1_1UniqueRandom.html',1,'cvflann']]],
  ['uniqueresultset',['UniqueResultSet',['https://docs.opencv.org/3.4.1/d4/dca/classcvflann_1_1UniqueResultSet.html',1,'cvflann']]],
  ['unordered_5fmap',['unordered_map',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmultimap',['unordered_multimap',['http://en.cppreference.com/w/cpp/container/unordered_multimap.html',1,'std']]],
  ['unordered_5fmultiset',['unordered_multiset',['http://en.cppreference.com/w/cpp/container/unordered_multiset.html',1,'std']]],
  ['unordered_5fset',['unordered_set',['http://en.cppreference.com/w/cpp/container/unordered_set.html',1,'std']]],
  ['unscentedkalmanfilter',['UnscentedKalmanFilter',['https://docs.opencv.org/3.4.1/de/d72/classcv_1_1tracking_1_1UnscentedKalmanFilter.html',1,'cv::tracking']]],
  ['unscentedkalmanfilterparams',['UnscentedKalmanFilterParams',['https://docs.opencv.org/3.4.1/da/d73/classcv_1_1tracking_1_1UnscentedKalmanFilterParams.html',1,'cv::tracking']]],
  ['untypedmatrix',['UntypedMatrix',['https://docs.opencv.org/3.4.1/d4/d5a/classcvflann_1_1UntypedMatrix.html',1,'cvflann']]],
  ['uses_5fallocator',['uses_allocator',['http://en.cppreference.com/w/cpp/memory/uses_allocator.html',1,'std']]]
];
