var searchData=
[
  ['caffeconverter',['CaffeConverter',['https://docs.opencv.org/3.4.1/d7/dc5/classcv_1_1dnn2_1_1CaffeConverter.html',1,'cv::dnn2']]],
  ['calibratecrf',['CalibrateCRF',['https://docs.opencv.org/3.4.1/dd/de3/classcv_1_1CalibrateCRF.html',1,'cv']]],
  ['calibratedebevec',['CalibrateDebevec',['https://docs.opencv.org/3.4.1/da/d27/classcv_1_1CalibrateDebevec.html',1,'cv']]],
  ['calibraterobertson',['CalibrateRobertson',['https://docs.opencv.org/3.4.1/d3/d30/classcv_1_1CalibrateRobertson.html',1,'cv']]],
  ['callback',['Callback',['https://docs.opencv.org/3.4.1/d0/d4f/classcv_1_1text_1_1ERFilter_1_1Callback.html',1,'cv::text::ERFilter']]],
  ['callmetadata',['CallMetaData',['https://docs.opencv.org/3.4.1/d4/dd9/structcvv_1_1impl_1_1CallMetaData.html',1,'cvv::impl']]],
  ['camera',['Camera',['https://docs.opencv.org/3.4.1/dc/d3a/classcv_1_1viz_1_1Camera.html',1,'cv::viz']]],
  ['cameraparam',['cameraParam',['https://docs.opencv.org/3.4.1/d3/d99/structcv_1_1datasets_1_1cameraParam.html',1,'cv::datasets']]],
  ['cameraparams',['CameraParams',['https://docs.opencv.org/3.4.1/d4/d0a/structcv_1_1detail_1_1CameraParams.html',1,'cv::detail']]],
  ['camerapos',['cameraPos',['https://docs.opencv.org/3.4.1/d1/d64/structcv_1_1datasets_1_1cameraPos.html',1,'cv::datasets']]],
  ['candidate',['Candidate',['https://docs.opencv.org/3.4.1/df/da3/structcv_1_1linemod_1_1QuantizedPyramid_1_1Candidate.html',1,'cv::linemod::QuantizedPyramid']]],
  ['cannyedgedetector',['CannyEdgeDetector',['https://docs.opencv.org/3.4.1/d0/d43/classcv_1_1cuda_1_1CannyEdgeDetector.html',1,'cv::cuda']]],
  ['cascadeclassifier',['CascadeClassifier',['https://docs.opencv.org/3.4.1/d9/d80/classcv_1_1cuda_1_1CascadeClassifier.html',1,'cv::cuda::CascadeClassifier'],['https://docs.opencv.org/3.4.1/d1/de5/classcv_1_1CascadeClassifier.html',1,'cv::CascadeClassifier']]],
  ['catalog',['catalog',['http://en.cppreference.com/w/cpp/locale/messages_base.html',1,'std::messages_byname::catalog'],['http://en.cppreference.com/w/cpp/locale/messages_base.html',1,'std::messages::catalog'],['http://en.cppreference.com/w/cpp/locale/messages_base.html',1,'std::messages_base::catalog']]],
  ['cauchy_5fdistribution',['cauchy_distribution',['http://en.cppreference.com/w/cpp/numeric/random/cauchy_distribution.html',1,'std']]],
  ['censuskernel',['CensusKernel',['https://docs.opencv.org/3.4.1/dc/d9a/structcv_1_1stereo_1_1CensusKernel.html',1,'cv::stereo']]],
  ['centi',['centi',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['cerr',['cerr',['http://en.cppreference.com/w/cpp/io/basic_ostream.html',1,'std']]],
  ['channelsprelulayer',['ChannelsPReLULayer',['https://docs.opencv.org/3.4.1/d7/de9/classcv_1_1dnn_1_1ChannelsPReLULayer.html',1,'cv::dnn']]],
  ['char_5ftraits',['char_traits',['http://en.cppreference.com/w/cpp/string/char_traits.html',1,'std']]],
  ['char_5ftype',['char_type',['http://en.cppreference.com/w/cpp/locale/money_get.html',1,'std::money_get::char_type'],['http://en.cppreference.com/w/cpp/locale/num_get.html',1,'std::num_get::char_type'],['http://en.cppreference.com/w/cpp/locale/time_put.html',1,'std::time_put_byname::char_type'],['http://en.cppreference.com/w/cpp/locale/time_get.html',1,'std::time_get::char_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate_byname::char_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct_byname::char_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages_byname::char_type'],['http://en.cppreference.com/w/cpp/locale/time_get.html',1,'std::time_get_byname::char_type'],['http://en.cppreference.com/w/cpp/locale/time_put.html',1,'std::time_put::char_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct::char_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate::char_type'],['http://en.cppreference.com/w/cpp/locale/num_put.html',1,'std::num_put::char_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages::char_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct_byname::char_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct::char_type'],['http://en.cppreference.com/w/cpp/locale/money_put.html',1,'std::money_put::char_type']]],
  ['charucoboard',['CharucoBoard',['https://docs.opencv.org/3.4.1/d0/d3c/classcv_1_1aruco_1_1CharucoBoard.html',1,'cv::aruco']]],
  ['chi_5fsquared_5fdistribution',['chi_squared_distribution',['http://en.cppreference.com/w/cpp/numeric/random/chi_squared_distribution.html',1,'std']]],
  ['chihistogramcostextractor',['ChiHistogramCostExtractor',['https://docs.opencv.org/3.4.1/dd/d43/classcv_1_1ChiHistogramCostExtractor.html',1,'cv']]],
  ['chisquaredistance',['ChiSquareDistance',['https://docs.opencv.org/3.4.1/dd/dd8/structcvflann_1_1ChiSquareDistance.html',1,'cvflann']]],
  ['choose_5fpolicy',['choose_policy',['https://docs.opencv.org/3.4.1/d5/da1/structcvflann_1_1anyimpl_1_1choose__policy.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20any_20_3e',['choose_policy&lt; any &gt;',['https://docs.opencv.org/3.4.1/d5/d51/structcvflann_1_1anyimpl_1_1choose__policy_3_01any_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20bool_20_3e',['choose_policy&lt; bool &gt;',['https://docs.opencv.org/3.4.1/d9/d10/structcvflann_1_1anyimpl_1_1choose__policy_3_01bool_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20float_20_3e',['choose_policy&lt; float &gt;',['https://docs.opencv.org/3.4.1/d2/d87/structcvflann_1_1anyimpl_1_1choose__policy_3_01float_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20char_20_3e',['choose_policy&lt; signed char &gt;',['https://docs.opencv.org/3.4.1/dc/d84/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01char_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20long_20_3e',['choose_policy&lt; signed long &gt;',['https://docs.opencv.org/3.4.1/d7/d22/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01long_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20signed_20short_20_3e',['choose_policy&lt; signed short &gt;',['https://docs.opencv.org/3.4.1/d3/d4a/structcvflann_1_1anyimpl_1_1choose__policy_3_01signed_01short_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20t_20_2a_3e',['choose_policy&lt; T *&gt;',['https://docs.opencv.org/3.4.1/d0/db0/structcvflann_1_1anyimpl_1_1choose__policy_3_01T_01_5_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20char_20_3e',['choose_policy&lt; unsigned char &gt;',['https://docs.opencv.org/3.4.1/dd/dd1/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01char_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20long_20_3e',['choose_policy&lt; unsigned long &gt;',['https://docs.opencv.org/3.4.1/d9/dcd/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01long_01_4.html',1,'cvflann::anyimpl']]],
  ['choose_5fpolicy_3c_20unsigned_20short_20_3e',['choose_policy&lt; unsigned short &gt;',['https://docs.opencv.org/3.4.1/d9/dd6/structcvflann_1_1anyimpl_1_1choose__policy_3_01unsigned_01short_01_4.html',1,'cvflann::anyimpl']]],
  ['cin',['cin',['http://en.cppreference.com/w/cpp/io/basic_istream.html',1,'std']]],
  ['circlesgridfinderparameters',['CirclesGridFinderParameters',['https://docs.opencv.org/3.4.1/d2/dd1/structcv_1_1CirclesGridFinderParameters.html',1,'cv']]],
  ['circlesgridfinderparameters2',['CirclesGridFinderParameters2',['https://docs.opencv.org/3.4.1/df/d58/structcv_1_1CirclesGridFinderParameters2.html',1,'cv']]],
  ['clahe',['CLAHE',['https://docs.opencv.org/3.4.1/db/d79/classcv_1_1cuda_1_1CLAHE.html',1,'cv::cuda::CLAHE'],['https://docs.opencv.org/3.4.1/d6/db6/classcv_1_1CLAHE.html',1,'cv::CLAHE']]],
  ['classifiercallback',['ClassifierCallback',['https://docs.opencv.org/3.4.1/db/dc0/classcv_1_1text_1_1OCRHMMDecoder_1_1ClassifierCallback.html',1,'cv::text::OCRHMMDecoder::ClassifierCallback'],['https://docs.opencv.org/3.4.1/de/d2d/classcv_1_1text_1_1OCRBeamSearchDecoder_1_1ClassifierCallback.html',1,'cv::text::OCRBeamSearchDecoder::ClassifierCallback']]],
  ['classifierthreshold',['ClassifierThreshold',['https://docs.opencv.org/3.4.1/d7/dd9/classcv_1_1ClassifierThreshold.html',1,'cv']]],
  ['clfmilboost',['ClfMilBoost',['https://docs.opencv.org/3.4.1/dc/d72/classcv_1_1ClfMilBoost.html',1,'cv']]],
  ['clfonlinestump',['ClfOnlineStump',['https://docs.opencv.org/3.4.1/dc/dac/classcv_1_1ClfOnlineStump.html',1,'cv']]],
  ['clock_5ft',['clock_t',['http://en.cppreference.com/w/cpp/chrono/c/clock_t.html',1,'std']]],
  ['clog',['clog',['http://en.cppreference.com/w/cpp/io/basic_ostream.html',1,'std']]],
  ['cmatch',['cmatch',['http://en.cppreference.com/w/cpp/regex/match_results.html',1,'std']]],
  ['codecvt',['codecvt',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std']]],
  ['codecvt_5fbase',['codecvt_base',['http://en.cppreference.com/w/cpp/locale/codecvt_base.html',1,'std']]],
  ['codecvt_5fbyname',['codecvt_byname',['http://en.cppreference.com/w/cpp/locale/codecvt_byname.html',1,'std']]],
  ['codecvt_5futf16',['codecvt_utf16',['http://en.cppreference.com/w/cpp/locale/codecvt_utf16.html',1,'std']]],
  ['codecvt_5futf8',['codecvt_utf8',['http://en.cppreference.com/w/cpp/locale/codecvt_utf8.html',1,'std']]],
  ['codecvt_5futf8_5futf16',['codecvt_utf8_utf16',['http://en.cppreference.com/w/cpp/locale/codecvt_utf8_utf16.html',1,'std']]],
  ['collate',['collate',['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std']]],
  ['collate_5fbyname',['collate_byname',['http://en.cppreference.com/w/cpp/locale/collate_byname.html',1,'std']]],
  ['color',['Color',['https://docs.opencv.org/3.4.1/d4/dba/classcv_1_1viz_1_1Color.html',1,'cv::viz']]],
  ['coloraverageinpainter',['ColorAverageInpainter',['https://docs.opencv.org/3.4.1/d1/dc6/classcv_1_1videostab_1_1ColorAverageInpainter.html',1,'cv::videostab']]],
  ['colorgradient',['ColorGradient',['https://docs.opencv.org/3.4.1/dc/d64/classcv_1_1linemod_1_1ColorGradient.html',1,'cv::linemod']]],
  ['colorinpainter',['ColorInpainter',['https://docs.opencv.org/3.4.1/d3/d2b/classcv_1_1videostab_1_1ColorInpainter.html',1,'cv::videostab']]],
  ['colormomenthash',['ColorMomentHash',['https://docs.opencv.org/3.4.1/df/d52/classcv_1_1img__hash_1_1ColorMomentHash.html',1,'cv::img_hash']]],
  ['combineddescriptor',['CombinedDescriptor',['https://docs.opencv.org/3.4.1/d4/d5b/classcv_1_1stereo_1_1CombinedDescriptor.html',1,'cv::stereo']]],
  ['commandlineparser',['CommandLineParser',['https://docs.opencv.org/3.4.1/d0/d2e/classcv_1_1CommandLineParser.html',1,'cv']]],
  ['common_5ftype',['common_type',['http://en.cppreference.com/w/cpp/types/common_type.html',1,'std']]],
  ['commonareainterptr',['CommonAreaInterPtr',['https://docs.opencv.org/3.4.1/d8/d3d/structcv_1_1cudev_1_1CommonAreaInterPtr.html',1,'cv::cudev']]],
  ['commonareainterptrsz',['CommonAreaInterPtrSz',['https://docs.opencv.org/3.4.1/db/d1c/structcv_1_1cudev_1_1CommonAreaInterPtrSz.html',1,'cv::cudev']]],
  ['comparesparsematnode',['CompareSparseMatNode',['../structanonymous__namespace_02_mx_array_8cpp_03_1_1_compare_sparse_mat_node.html',1,'anonymous_namespace{MxArray.cpp}']]],
  ['comparet',['CompareT',['https://docs.opencv.org/3.4.1/d2/d76/structcvflann_1_1Heap_1_1CompareT.html',1,'cvflann::Heap']]],
  ['complex',['complex',['http://en.cppreference.com/w/cpp/numeric/complex.html',1,'std::complex'],['https://docs.opencv.org/3.4.1/da/df6/classcv_1_1Complex.html',1,'cv::Complex&lt; _Tp &gt;']]],
  ['compositeindex',['CompositeIndex',['https://docs.opencv.org/3.4.1/dc/d59/classcvflann_1_1CompositeIndex.html',1,'cvflann']]],
  ['compositeindexparams',['CompositeIndexParams',['https://docs.opencv.org/3.4.1/db/d3f/structcvflann_1_1CompositeIndexParams.html',1,'cvflann::CompositeIndexParams'],['https://docs.opencv.org/3.4.1/d5/d94/structcv_1_1flann_1_1CompositeIndexParams.html',1,'cv::flann::CompositeIndexParams']]],
  ['compressedrectilinearportraitprojector',['CompressedRectilinearPortraitProjector',['https://docs.opencv.org/3.4.1/d0/ded/structcv_1_1detail_1_1CompressedRectilinearPortraitProjector.html',1,'cv::detail']]],
  ['compressedrectilinearportraitwarper',['CompressedRectilinearPortraitWarper',['https://docs.opencv.org/3.4.1/dd/dc8/classcv_1_1detail_1_1CompressedRectilinearPortraitWarper.html',1,'cv::detail::CompressedRectilinearPortraitWarper'],['https://docs.opencv.org/3.4.1/de/d9a/classcv_1_1CompressedRectilinearPortraitWarper.html',1,'cv::CompressedRectilinearPortraitWarper']]],
  ['compressedrectilinearprojector',['CompressedRectilinearProjector',['https://docs.opencv.org/3.4.1/db/dbb/structcv_1_1detail_1_1CompressedRectilinearProjector.html',1,'cv::detail']]],
  ['compressedrectilinearwarper',['CompressedRectilinearWarper',['https://docs.opencv.org/3.4.1/dd/dbe/classcv_1_1detail_1_1CompressedRectilinearWarper.html',1,'cv::detail::CompressedRectilinearWarper'],['https://docs.opencv.org/3.4.1/d0/dd5/classcv_1_1CompressedRectilinearWarper.html',1,'cv::CompressedRectilinearWarper']]],
  ['concatlayer',['ConcatLayer',['https://docs.opencv.org/3.4.1/da/d5c/classcv_1_1dnn_1_1ConcatLayer.html',1,'cv::dnn']]],
  ['condition_5fvariable',['condition_variable',['http://en.cppreference.com/w/cpp/thread/condition_variable.html',1,'std']]],
  ['condition_5fvariable_5fany',['condition_variable_any',['http://en.cppreference.com/w/cpp/thread/condition_variable_any.html',1,'std']]],
  ['conditional',['conditional',['http://en.cppreference.com/w/cpp/types/conditional.html',1,'std']]],
  ['config',['Config',['https://docs.opencv.org/3.4.1/d0/ded/structcv_1_1face_1_1FacemarkAAM_1_1Config.html',1,'cv::face::FacemarkAAM']]],
  ['conjgradsolver',['ConjGradSolver',['https://docs.opencv.org/3.4.1/d0/d21/classcv_1_1ConjGradSolver.html',1,'cv']]],
  ['consistentmosaicinpainter',['ConsistentMosaicInpainter',['https://docs.opencv.org/3.4.1/d9/dba/classcv_1_1videostab_1_1ConsistentMosaicInpainter.html',1,'cv::videostab']]],
  ['constantptr',['ConstantPtr',['https://docs.opencv.org/3.4.1/d5/db7/structcv_1_1cudev_1_1ConstantPtr.html',1,'cv::cudev']]],
  ['constantptrsz',['ConstantPtrSz',['https://docs.opencv.org/3.4.1/d2/df7/structcv_1_1cudev_1_1ConstantPtrSz.html',1,'cv::cudev']]],
  ['constmap',['ConstMap',['../class_const_map.html',1,'']]],
  ['context',['Context',['https://docs.opencv.org/3.4.1/d1/d45/classcv_1_1ocl_1_1Context.html',1,'cv::ocl']]],
  ['contourfitting',['ContourFitting',['https://docs.opencv.org/3.4.1/d5/d72/classcv_1_1ximgproc_1_1ContourFitting.html',1,'cv::ximgproc']]],
  ['converttuple',['ConvertTuple',['https://docs.opencv.org/3.4.1/d9/d6a/structcv_1_1cudev_1_1ConvertTuple.html',1,'cv::cudev']]],
  ['convolution',['Convolution',['https://docs.opencv.org/3.4.1/d4/d25/classcv_1_1cuda_1_1Convolution.html',1,'cv::cuda']]],
  ['convolutionlayer',['ConvolutionLayer',['https://docs.opencv.org/3.4.1/d5/dcf/classcv_1_1dnn_1_1ConvolutionLayer.html',1,'cv::dnn']]],
  ['cornernesscriteria',['CornernessCriteria',['https://docs.opencv.org/3.4.1/dd/d63/classcv_1_1cuda_1_1CornernessCriteria.html',1,'cv::cuda']]],
  ['cornersdetector',['CornersDetector',['https://docs.opencv.org/3.4.1/de/d95/classcv_1_1cuda_1_1CornersDetector.html',1,'cv::cuda']]],
  ['cos_5ffunc',['cos_func',['https://docs.opencv.org/3.4.1/d6/dfb/structcv_1_1cudev_1_1cos__func.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20double_20_3e',['cos_func&lt; double &gt;',['https://docs.opencv.org/3.4.1/db/d23/structcv_1_1cudev_1_1cos__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20float_20_3e',['cos_func&lt; float &gt;',['https://docs.opencv.org/3.4.1/dd/d7a/structcv_1_1cudev_1_1cos__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20schar_20_3e',['cos_func&lt; schar &gt;',['https://docs.opencv.org/3.4.1/dc/d25/structcv_1_1cudev_1_1cos__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20short_20_3e',['cos_func&lt; short &gt;',['https://docs.opencv.org/3.4.1/d7/d03/structcv_1_1cudev_1_1cos__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20uchar_20_3e',['cos_func&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/dd/d3d/structcv_1_1cudev_1_1cos__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20uint_20_3e',['cos_func&lt; uint &gt;',['https://docs.opencv.org/3.4.1/da/dc1/structcv_1_1cudev_1_1cos__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['cos_5ffunc_3c_20ushort_20_3e',['cos_func&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/df/d35/structcv_1_1cudev_1_1cos__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc',['cosh_func',['https://docs.opencv.org/3.4.1/dc/d8a/structcv_1_1cudev_1_1cosh__func.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20double_20_3e',['cosh_func&lt; double &gt;',['https://docs.opencv.org/3.4.1/d5/d3a/structcv_1_1cudev_1_1cosh__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20float_20_3e',['cosh_func&lt; float &gt;',['https://docs.opencv.org/3.4.1/db/d8d/structcv_1_1cudev_1_1cosh__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20schar_20_3e',['cosh_func&lt; schar &gt;',['https://docs.opencv.org/3.4.1/df/dd8/structcv_1_1cudev_1_1cosh__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20short_20_3e',['cosh_func&lt; short &gt;',['https://docs.opencv.org/3.4.1/dc/d8a/structcv_1_1cudev_1_1cosh__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20uchar_20_3e',['cosh_func&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/de/d73/structcv_1_1cudev_1_1cosh__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20uint_20_3e',['cosh_func&lt; uint &gt;',['https://docs.opencv.org/3.4.1/d5/ddd/structcv_1_1cudev_1_1cosh__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['cosh_5ffunc_3c_20ushort_20_3e',['cosh_func&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/d2/dd3/structcv_1_1cudev_1_1cosh__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['countnonzeroexprbody',['CountNonZeroExprBody',['https://docs.opencv.org/3.4.1/dd/d49/structcv_1_1cudev_1_1CountNonZeroExprBody.html',1,'cv::cudev']]],
  ['cout',['cout',['http://en.cppreference.com/w/cpp/io/basic_ostream.html',1,'std']]],
  ['cparams',['CParams',['https://docs.opencv.org/3.4.1/d8/dd8/structcv_1_1face_1_1CParams.html',1,'cv::face']]],
  ['creal32_5ft',['creal32_T',['../structcreal32___t.html',1,'']]],
  ['creal64_5ft',['creal64_T',['../structcreal64___t.html',1,'']]],
  ['creal_5ft',['creal_T',['../structcreal___t.html',1,'']]],
  ['creatornotfound',['CreatorNotFound',['https://docs.opencv.org/3.4.1/db/d35/classcvflann_1_1CreatorNotFound.html',1,'cvflann']]],
  ['cregex_5fiterator',['cregex_iterator',['http://en.cppreference.com/w/cpp/regex/regex_iterator.html',1,'std']]],
  ['cregex_5ftoken_5fiterator',['cregex_token_iterator',['http://en.cppreference.com/w/cpp/regex/regex_token_iterator.html',1,'std']]],
  ['croplayer',['CropLayer',['https://docs.opencv.org/3.4.1/d7/d86/classcv_1_1dnn_1_1CropLayer.html',1,'cv::dnn']]],
  ['csub_5fmatch',['csub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['ct_5fassert_5ffailure',['CT_ASSERT_FAILURE',['https://docs.opencv.org/3.4.1/da/d73/structNcvCTprep_1_1CT__ASSERT__FAILURE.html',1,'NcvCTprep']]],
  ['ct_5fassert_5ffailure_3c_20true_20_3e',['CT_ASSERT_FAILURE&lt; true &gt;',['https://docs.opencv.org/3.4.1/dc/dcf/structNcvCTprep_1_1CT__ASSERT__FAILURE_3_01true_01_4.html',1,'NcvCTprep']]],
  ['ctype',['ctype',['http://en.cppreference.com/w/cpp/locale/ctype.html',1,'std']]],
  ['ctype_5fbase',['ctype_base',['http://en.cppreference.com/w/cpp/locale/ctype_base.html',1,'std']]],
  ['ctype_5fbyname',['ctype_byname',['http://en.cppreference.com/w/cpp/locale/ctype_byname.html',1,'std']]],
  ['cubicinterptr',['CubicInterPtr',['https://docs.opencv.org/3.4.1/d3/def/structcv_1_1cudev_1_1CubicInterPtr.html',1,'cv::cudev']]],
  ['cubicinterptrsz',['CubicInterPtrSz',['https://docs.opencv.org/3.4.1/d2/d00/structcv_1_1cudev_1_1CubicInterPtrSz.html',1,'cv::cudev']]],
  ['custompattern',['CustomPattern',['https://docs.opencv.org/3.4.1/d3/d3e/classcv_1_1ccalib_1_1CustomPattern.html',1,'cv::ccalib']]],
  ['cv16suf',['Cv16suf',['https://docs.opencv.org/3.4.1/dd/d0f/unionCv16suf.html',1,'']]],
  ['cv32suf',['Cv32suf',['https://docs.opencv.org/3.4.1/d9/df3/unionCv32suf.html',1,'']]],
  ['cv64suf',['Cv64suf',['https://docs.opencv.org/3.4.1/de/d55/unionCv64suf.html',1,'']]],
  ['cvabstractcamera',['CvAbstractCamera',['https://docs.opencv.org/3.4.1/d0/de8/interfaceCvAbstractCamera.html',1,'']]],
  ['cvattrlist',['CvAttrList',['https://docs.opencv.org/3.4.1/df/dea/structCvAttrList.html',1,'']]],
  ['cvavgcomp',['CvAvgComp',['https://docs.opencv.org/3.4.1/d5/d8a/structCvAvgComp.html',1,'']]],
  ['cvbox2d',['CvBox2D',['https://docs.opencv.org/3.4.1/da/d13/structCvBox2D.html',1,'']]],
  ['cvchain',['CvChain',['https://docs.opencv.org/3.4.1/d9/d08/structCvChain.html',1,'']]],
  ['cvchainptreader',['CvChainPtReader',['https://docs.opencv.org/3.4.1/d9/db9/structCvChainPtReader.html',1,'']]],
  ['cvconnectedcomp',['CvConnectedComp',['https://docs.opencv.org/3.4.1/d3/df6/structCvConnectedComp.html',1,'']]],
  ['cvcontour',['CvContour',['https://docs.opencv.org/3.4.1/dd/deb/structCvContour.html',1,'']]],
  ['cvconvexitydefect',['CvConvexityDefect',['https://docs.opencv.org/3.4.1/d7/dec/structCvConvexityDefect.html',1,'']]],
  ['cvfeatureevaluator',['CvFeatureEvaluator',['https://docs.opencv.org/3.4.1/d0/d0b/classcv_1_1CvFeatureEvaluator.html',1,'cv']]],
  ['cvfeatureparams',['CvFeatureParams',['https://docs.opencv.org/3.4.1/db/dfc/classcv_1_1CvFeatureParams.html',1,'cv']]],
  ['cvfilenode',['CvFileNode',['https://docs.opencv.org/3.4.1/dc/d73/structCvFileNode.html',1,'']]],
  ['cvfont',['CvFont',['https://docs.opencv.org/3.4.1/db/d2b/structCvFont.html',1,'']]],
  ['cvgraph',['CvGraph',['https://docs.opencv.org/3.4.1/db/da6/structCvGraph.html',1,'']]],
  ['cvgraphedge',['CvGraphEdge',['https://docs.opencv.org/3.4.1/d0/db1/structCvGraphEdge.html',1,'']]],
  ['cvgraphscanner',['CvGraphScanner',['https://docs.opencv.org/3.4.1/d6/d89/structCvGraphScanner.html',1,'']]],
  ['cvgraphvtx',['CvGraphVtx',['https://docs.opencv.org/3.4.1/d3/d89/structCvGraphVtx.html',1,'']]],
  ['cvgraphvtx2d',['CvGraphVtx2D',['https://docs.opencv.org/3.4.1/df/d9e/structCvGraphVtx2D.html',1,'']]],
  ['cvhaarclassifier',['CvHaarClassifier',['https://docs.opencv.org/3.4.1/d5/de9/structCvHaarClassifier.html',1,'']]],
  ['cvhaarclassifiercascade',['CvHaarClassifierCascade',['https://docs.opencv.org/3.4.1/d6/d3d/structCvHaarClassifierCascade.html',1,'']]],
  ['cvhaarevaluator',['CvHaarEvaluator',['https://docs.opencv.org/3.4.1/db/d35/classcv_1_1CvHaarEvaluator.html',1,'cv']]],
  ['cvhaarfeature',['CvHaarFeature',['https://docs.opencv.org/3.4.1/d7/d82/structCvHaarFeature.html',1,'']]],
  ['cvhaarfeatureparams',['CvHaarFeatureParams',['https://docs.opencv.org/3.4.1/d9/d90/classcv_1_1CvHaarFeatureParams.html',1,'cv']]],
  ['cvhaarstageclassifier',['CvHaarStageClassifier',['https://docs.opencv.org/3.4.1/db/df3/structCvHaarStageClassifier.html',1,'']]],
  ['cvhaldft',['cvhalDFT',['https://docs.opencv.org/3.4.1/de/d27/structcvhalDFT.html',1,'']]],
  ['cvhalfilter2d',['cvhalFilter2D',['https://docs.opencv.org/3.4.1/d2/da8/structcvhalFilter2D.html',1,'']]],
  ['cvhalkeypoint',['cvhalKeyPoint',['https://docs.opencv.org/3.4.1/d9/daa/structcvhalKeyPoint.html',1,'']]],
  ['cvhistogram',['CvHistogram',['https://docs.opencv.org/3.4.1/df/df3/structCvHistogram.html',1,'']]],
  ['cvhogevaluator',['CvHOGEvaluator',['https://docs.opencv.org/3.4.1/d2/dd9/classcv_1_1CvHOGEvaluator.html',1,'cv']]],
  ['cvhogfeatureparams',['CvHOGFeatureParams',['https://docs.opencv.org/3.4.1/d4/d4a/structcv_1_1CvHOGFeatureParams.html',1,'cv']]],
  ['cvhumoments',['CvHuMoments',['https://docs.opencv.org/3.4.1/dd/d46/structCvHuMoments.html',1,'']]],
  ['cvkalman',['CvKalman',['https://docs.opencv.org/3.4.1/d5/de6/structCvKalman.html',1,'']]],
  ['cvlbpevaluator',['CvLBPEvaluator',['https://docs.opencv.org/3.4.1/d1/d26/classcv_1_1CvLBPEvaluator.html',1,'cv']]],
  ['cvlbpfeatureparams',['CvLBPFeatureParams',['https://docs.opencv.org/3.4.1/d2/d3c/structcv_1_1CvLBPFeatureParams.html',1,'cv']]],
  ['cvlevmarq',['CvLevMarq',['https://docs.opencv.org/3.4.1/d2/d70/classCvLevMarq.html',1,'']]],
  ['cvlineiterator',['CvLineIterator',['https://docs.opencv.org/3.4.1/d9/d22/structCvLineIterator.html',1,'']]],
  ['cvmat',['CvMat',['https://docs.opencv.org/3.4.1/d3/db2/structCvMat.html',1,'']]],
  ['cvmatnd',['CvMatND',['https://docs.opencv.org/3.4.1/d4/d4c/structCvMatND.html',1,'']]],
  ['cvmemblock',['CvMemBlock',['https://docs.opencv.org/3.4.1/dd/d24/structCvMemBlock.html',1,'']]],
  ['cvmemstorage',['CvMemStorage',['https://docs.opencv.org/3.4.1/db/d76/structCvMemStorage.html',1,'']]],
  ['cvmemstoragepos',['CvMemStoragePos',['https://docs.opencv.org/3.4.1/da/d36/structCvMemStoragePos.html',1,'']]],
  ['cvmoduleinfo',['CvModuleInfo',['https://docs.opencv.org/3.4.1/df/db0/structCvModuleInfo.html',1,'']]],
  ['cvmoments',['CvMoments',['https://docs.opencv.org/3.4.1/d6/dc6/structCvMoments.html',1,'']]],
  ['cvnarrayiterator',['CvNArrayIterator',['https://docs.opencv.org/3.4.1/d3/da5/structCvNArrayIterator.html',1,'']]],
  ['cvparams',['CvParams',['https://docs.opencv.org/3.4.1/db/d7c/classcv_1_1CvParams.html',1,'cv']]],
  ['cvphotocamera',['CvPhotoCamera',['https://docs.opencv.org/3.4.1/d4/d1d/interfaceCvPhotoCamera.html',1,'']]],
  ['cvphotocameradelegate_20_2dp_2dp',['CvPhotoCameraDelegate -p-p',['https://docs.opencv.org/3.4.1/d7/d2f/protocolCvPhotoCameraDelegate_01-p.html',1,'']]],
  ['cvpluginfuncinfo',['CvPluginFuncInfo',['https://docs.opencv.org/3.4.1/df/d6a/structCvPluginFuncInfo.html',1,'']]],
  ['cvpoint',['CvPoint',['https://docs.opencv.org/3.4.1/dc/dd1/structCvPoint.html',1,'']]],
  ['cvpoint2d32f',['CvPoint2D32f',['https://docs.opencv.org/3.4.1/da/db6/structCvPoint2D32f.html',1,'']]],
  ['cvpoint2d64f',['CvPoint2D64f',['https://docs.opencv.org/3.4.1/df/d5d/structCvPoint2D64f.html',1,'']]],
  ['cvpoint3d32f',['CvPoint3D32f',['https://docs.opencv.org/3.4.1/d7/db2/structCvPoint3D32f.html',1,'']]],
  ['cvpoint3d64f',['CvPoint3D64f',['https://docs.opencv.org/3.4.1/d4/da0/structCvPoint3D64f.html',1,'']]],
  ['cvrect',['CvRect',['https://docs.opencv.org/3.4.1/d0/d76/structCvRect.html',1,'']]],
  ['cvscalar',['CvScalar',['https://docs.opencv.org/3.4.1/d6/db3/structCvScalar.html',1,'']]],
  ['cvseq',['CvSeq',['https://docs.opencv.org/3.4.1/d6/dde/structCvSeq.html',1,'']]],
  ['cvseqblock',['CvSeqBlock',['https://docs.opencv.org/3.4.1/dd/de2/structCvSeqBlock.html',1,'']]],
  ['cvseqreader',['CvSeqReader',['https://docs.opencv.org/3.4.1/d8/de9/structCvSeqReader.html',1,'']]],
  ['cvseqwriter',['CvSeqWriter',['https://docs.opencv.org/3.4.1/d6/d41/structCvSeqWriter.html',1,'']]],
  ['cvset',['CvSet',['https://docs.opencv.org/3.4.1/d8/dad/structCvSet.html',1,'']]],
  ['cvsetelem',['CvSetElem',['https://docs.opencv.org/3.4.1/d0/df0/structCvSetElem.html',1,'']]],
  ['cvsize',['CvSize',['https://docs.opencv.org/3.4.1/da/dcb/structCvSize.html',1,'']]],
  ['cvsize2d32f',['CvSize2D32f',['https://docs.opencv.org/3.4.1/dd/d16/structCvSize2D32f.html',1,'']]],
  ['cvslice',['CvSlice',['https://docs.opencv.org/3.4.1/d5/d3e/structCvSlice.html',1,'']]],
  ['cvsparsemat',['CvSparseMat',['https://docs.opencv.org/3.4.1/dd/d4b/structCvSparseMat.html',1,'']]],
  ['cvsparsematiterator',['CvSparseMatIterator',['https://docs.opencv.org/3.4.1/d8/d39/structCvSparseMatIterator.html',1,'']]],
  ['cvsparsenode',['CvSparseNode',['https://docs.opencv.org/3.4.1/df/d7a/structCvSparseNode.html',1,'']]],
  ['cvstereobmstate',['CvStereoBMState',['https://docs.opencv.org/3.4.1/dd/d3f/structCvStereoBMState.html',1,'']]],
  ['cvstring',['CvString',['https://docs.opencv.org/3.4.1/d7/d16/structCvString.html',1,'']]],
  ['cvstringhashnode',['CvStringHashNode',['https://docs.opencv.org/3.4.1/da/dbd/structCvStringHashNode.html',1,'']]],
  ['cvtermcriteria',['CvTermCriteria',['https://docs.opencv.org/3.4.1/d8/d2b/structCvTermCriteria.html',1,'']]],
  ['cvtreenodeiterator',['CvTreeNodeIterator',['https://docs.opencv.org/3.4.1/d7/d14/structCvTreeNodeIterator.html',1,'']]],
  ['cvtype',['CvType',['https://docs.opencv.org/3.4.1/d3/dba/structCvType.html',1,'CvType'],['https://docs.opencv.org/3.4.1/d1/def/structcv_1_1flann_1_1CvType.html',1,'cv::flann::CvType&lt; class &gt;']]],
  ['cvtype_3c_20char_20_3e',['CvType&lt; char &gt;',['https://docs.opencv.org/3.4.1/dc/d89/structcv_1_1flann_1_1CvType_3_01char_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20double_20_3e',['CvType&lt; double &gt;',['https://docs.opencv.org/3.4.1/dc/d69/structcv_1_1flann_1_1CvType_3_01double_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20float_20_3e',['CvType&lt; float &gt;',['https://docs.opencv.org/3.4.1/dc/dd6/structcv_1_1flann_1_1CvType_3_01float_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20short_20_3e',['CvType&lt; short &gt;',['https://docs.opencv.org/3.4.1/d2/def/structcv_1_1flann_1_1CvType_3_01short_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20unsigned_20char_20_3e',['CvType&lt; unsigned char &gt;',['https://docs.opencv.org/3.4.1/d7/da5/structcv_1_1flann_1_1CvType_3_01unsigned_01char_01_4.html',1,'cv::flann']]],
  ['cvtype_3c_20unsigned_20short_20_3e',['CvType&lt; unsigned short &gt;',['https://docs.opencv.org/3.4.1/d9/d57/structcv_1_1flann_1_1CvType_3_01unsigned_01short_01_4.html',1,'cv::flann']]],
  ['cvtypeinfo',['CvTypeInfo',['https://docs.opencv.org/3.4.1/d7/d7c/structCvTypeInfo.html',1,'']]],
  ['cvvideocamera',['CvVideoCamera',['https://docs.opencv.org/3.4.1/db/da9/interfaceCvVideoCamera.html',1,'']]],
  ['cvvideocameradelegate_20_2dp_2dp',['CvVideoCameraDelegate -p-p',['https://docs.opencv.org/3.4.1/d3/d54/protocolCvVideoCameraDelegate_01-p.html',1,'']]],
  ['cylindricalportraitprojector',['CylindricalPortraitProjector',['https://docs.opencv.org/3.4.1/df/d3f/structcv_1_1detail_1_1CylindricalPortraitProjector.html',1,'cv::detail']]],
  ['cylindricalportraitwarper',['CylindricalPortraitWarper',['https://docs.opencv.org/3.4.1/dd/d19/classcv_1_1detail_1_1CylindricalPortraitWarper.html',1,'cv::detail']]],
  ['cylindricalprojector',['CylindricalProjector',['https://docs.opencv.org/3.4.1/dd/d96/structcv_1_1detail_1_1CylindricalProjector.html',1,'cv::detail']]],
  ['cylindricalwarper',['CylindricalWarper',['https://docs.opencv.org/3.4.1/d3/dd6/classcv_1_1detail_1_1CylindricalWarper.html',1,'cv::detail::CylindricalWarper'],['https://docs.opencv.org/3.4.1/d7/df6/classcv_1_1CylindricalWarper.html',1,'cv::CylindricalWarper']]],
  ['cylindricalwarpergpu',['CylindricalWarperGpu',['https://docs.opencv.org/3.4.1/d9/dbd/classcv_1_1detail_1_1CylindricalWarperGpu.html',1,'cv::detail']]]
];
