var searchData=
[
  ['saliency',['Saliency',['https://docs.opencv.org/3.4.1/d9/dcd/classcv_1_1saliency_1_1Saliency.html',1,'cv::saliency']]],
  ['satcasthelper',['SatCastHelper',['https://docs.opencv.org/3.4.1/dc/db0/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_201_2c_20vecd_20_3e',['SatCastHelper&lt; 1, VecD &gt;',['https://docs.opencv.org/3.4.1/d2/d31/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_011_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_202_2c_20vecd_20_3e',['SatCastHelper&lt; 2, VecD &gt;',['https://docs.opencv.org/3.4.1/dc/dbc/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_012_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_203_2c_20vecd_20_3e',['SatCastHelper&lt; 3, VecD &gt;',['https://docs.opencv.org/3.4.1/d8/dbe/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_013_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_204_2c_20vecd_20_3e',['SatCastHelper&lt; 4, VecD &gt;',['https://docs.opencv.org/3.4.1/df/d18/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_014_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['saturate_5fcast_5ffp16_5ffunc',['saturate_cast_fp16_func',['https://docs.opencv.org/3.4.1/de/d9b/structcv_1_1cudev_1_1saturate__cast__fp16__func.html',1,'cv::cudev']]],
  ['saturate_5fcast_5ffp16_5ffunc_3c_20float_2c_20short_20_3e',['saturate_cast_fp16_func&lt; float, short &gt;',['https://docs.opencv.org/3.4.1/d3/d11/structcv_1_1cudev_1_1saturate__cast__fp16__func_3_01float_00_01short_01_4.html',1,'cv::cudev']]],
  ['saturate_5fcast_5ffp16_5ffunc_3c_20short_2c_20float_20_3e',['saturate_cast_fp16_func&lt; short, float &gt;',['https://docs.opencv.org/3.4.1/dc/dc5/structcv_1_1cudev_1_1saturate__cast__fp16__func_3_01short_00_01float_01_4.html',1,'cv::cudev']]],
  ['saturate_5fcast_5ffunc',['saturate_cast_func',['https://docs.opencv.org/3.4.1/dc/d99/structcv_1_1cudev_1_1saturate__cast__func.html',1,'cv::cudev']]],
  ['savedindexparams',['SavedIndexParams',['https://docs.opencv.org/3.4.1/de/de8/structcv_1_1flann_1_1SavedIndexParams.html',1,'cv::flann::SavedIndexParams'],['https://docs.opencv.org/3.4.1/dc/d2a/structcvflann_1_1SavedIndexParams.html',1,'cvflann::SavedIndexParams']]],
  ['scalar_5f',['Scalar_',['https://docs.opencv.org/3.4.1/d1/da0/classcv_1_1Scalar__.html',1,'cv']]],
  ['scalar_5f_3c_20double_20_3e',['Scalar_&lt; double &gt;',['https://docs.opencv.org/3.4.1/d1/da0/classcv_1_1Scalar__.html',1,'Scalar_&lt; double &gt;'],['https://docs.opencv.org/3.4.1/d1/da0/classcv_1_1Scalar__.html',1,'cv::Scalar_&lt; double &gt;']]],
  ['scalelayer',['ScaleLayer',['https://docs.opencv.org/3.4.1/dd/dde/classcv_1_1dnn_1_1ScaleLayer.html',1,'cv::dnn']]],
  ['scharrxptr',['ScharrXPtr',['https://docs.opencv.org/3.4.1/d7/d71/structcv_1_1cudev_1_1ScharrXPtr.html',1,'cv::cudev']]],
  ['scharrxptrsz',['ScharrXPtrSz',['https://docs.opencv.org/3.4.1/d2/d88/structcv_1_1cudev_1_1ScharrXPtrSz.html',1,'cv::cudev']]],
  ['scharryptr',['ScharrYPtr',['https://docs.opencv.org/3.4.1/d0/d70/structcv_1_1cudev_1_1ScharrYPtr.html',1,'cv::cudev']]],
  ['scharryptrsz',['ScharrYPtrSz',['https://docs.opencv.org/3.4.1/dd/def/structcv_1_1cudev_1_1ScharrYPtrSz.html',1,'cv::cudev']]],
  ['scoped_5fallocator_5fadaptor',['scoped_allocator_adaptor',['http://en.cppreference.com/w/cpp/memory/scoped_allocator_adaptor.html',1,'std']]],
  ['seamfinder',['SeamFinder',['https://docs.opencv.org/3.4.1/d7/d09/classcv_1_1detail_1_1SeamFinder.html',1,'cv::detail']]],
  ['searchparams',['SearchParams',['https://docs.opencv.org/3.4.1/d6/d59/structcvflann_1_1SearchParams.html',1,'cvflann::SearchParams'],['https://docs.opencv.org/3.4.1/d5/d03/structcv_1_1flann_1_1SearchParams.html',1,'cv::flann::SearchParams']]],
  ['seconds',['seconds',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['seed_5fseq',['seed_seq',['http://en.cppreference.com/w/cpp/numeric/random/seed_seq.html',1,'std']]],
  ['segmentationparameters',['SegmentationParameters',['https://docs.opencv.org/3.4.1/d9/dbf/structcv_1_1bioinspired_1_1SegmentationParameters.html',1,'cv::bioinspired']]],
  ['selectif',['SelectIf',['https://docs.opencv.org/3.4.1/d8/d1b/structcv_1_1cudev_1_1SelectIf.html',1,'cv::cudev']]],
  ['selectif_3c_20false_2c_20thentype_2c_20elsetype_20_3e',['SelectIf&lt; false, ThenType, ElseType &gt;',['https://docs.opencv.org/3.4.1/dd/da7/structcv_1_1cudev_1_1SelectIf_3_01false_00_01ThenType_00_01ElseType_01_4.html',1,'cv::cudev']]],
  ['selectivesearchsegmentation',['SelectiveSearchSegmentation',['https://docs.opencv.org/3.4.1/d6/d6d/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentation.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategy',['SelectiveSearchSegmentationStrategy',['https://docs.opencv.org/3.4.1/dc/d7a/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategy.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategycolor',['SelectiveSearchSegmentationStrategyColor',['https://docs.opencv.org/3.4.1/de/dab/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyColor.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategyfill',['SelectiveSearchSegmentationStrategyFill',['https://docs.opencv.org/3.4.1/d9/db3/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyFill.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategymultiple',['SelectiveSearchSegmentationStrategyMultiple',['https://docs.opencv.org/3.4.1/d8/d8e/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyMultiple.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategysize',['SelectiveSearchSegmentationStrategySize',['https://docs.opencv.org/3.4.1/d0/d10/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategySize.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategytexture',['SelectiveSearchSegmentationStrategyTexture',['https://docs.opencv.org/3.4.1/d6/d17/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyTexture.html',1,'cv::ximgproc::segmentation']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ofstream&lt; Char &gt;::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::strstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_istream&lt; Char &gt;::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_ifstream&lt; Char &gt;::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_fstream&lt; Char &gt;::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ostringstream&lt; Char &gt;::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wiostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_istringstream&lt; Char &gt;::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ostream&lt; Char &gt;::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_stringstream&lt; Char &gt;::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_iostream&lt; Char &gt;::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istrstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wistringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wstringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wfstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::stringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wistream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostrstream::sentry']]],
  ['seq',['Seq',['https://docs.opencv.org/3.4.1/de/dd1/classcv_1_1Seq.html',1,'cv']]],
  ['seqiterator',['SeqIterator',['https://docs.opencv.org/3.4.1/dd/d28/classcv_1_1SeqIterator.html',1,'cv']]],
  ['seqreader',['SeqReader',['https://docs.opencv.org/3.4.1/dc/db7/structcv_1_1FileNodeIterator_1_1SeqReader.html',1,'cv::FileNodeIterator']]],
  ['set',['set',['http://en.cppreference.com/w/cpp/container/set.html',1,'std']]],
  ['set_3c_20distindex_20_3e',['set&lt; DistIndex &gt;',['http://en.cppreference.com/w/cpp/container/set.html',1,'std']]],
  ['sfmlibmveuclideanreconstruction',['SFMLibmvEuclideanReconstruction',['https://docs.opencv.org/3.4.1/de/d42/classcv_1_1sfm_1_1SFMLibmvEuclideanReconstruction.html',1,'cv::sfm']]],
  ['shapecontextdistanceextractor',['ShapeContextDistanceExtractor',['https://docs.opencv.org/3.4.1/d8/de3/classcv_1_1ShapeContextDistanceExtractor.html',1,'cv']]],
  ['shapedistanceextractor',['ShapeDistanceExtractor',['https://docs.opencv.org/3.4.1/dc/dbf/classcv_1_1ShapeDistanceExtractor.html',1,'cv']]],
  ['shapetransformer',['ShapeTransformer',['https://docs.opencv.org/3.4.1/df/dfe/classcv_1_1ShapeTransformer.html',1,'cv']]],
  ['shared_5ffuture',['shared_future',['http://en.cppreference.com/w/cpp/thread/shared_future.html',1,'std']]],
  ['shared_5flock',['shared_lock',['http://en.cppreference.com/w/cpp/thread/shared_lock.html',1,'std']]],
  ['shared_5flock_5fguard',['shared_lock_guard',['https://docs.opencv.org/3.4.1/d9/d7f/classcv_1_1utils_1_1shared__lock__guard.html',1,'cv::utils']]],
  ['shared_5fptr',['shared_ptr',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5ftimed_5fmutex',['shared_timed_mutex',['http://en.cppreference.com/w/cpp/thread/shared_timed_mutex.html',1,'std']]],
  ['shiftlayer',['ShiftLayer',['https://docs.opencv.org/3.4.1/d3/dd8/classcv_1_1dnn_1_1ShiftLayer.html',1,'cv::dnn']]],
  ['shuffle_5forder_5fengine',['shuffle_order_engine',['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine.html',1,'std']]],
  ['sift',['SIFT',['https://docs.opencv.org/3.4.1/d5/d3c/classcv_1_1xfeatures2d_1_1SIFT.html',1,'cv::xfeatures2d']]],
  ['sig_5fatomic_5ft',['sig_atomic_t',['http://en.cppreference.com/w/cpp/utility/program/sig_atomic_t.html',1,'std']]],
  ['sigmoidlayer',['SigmoidLayer',['https://docs.opencv.org/3.4.1/dc/d09/classcv_1_1dnn_1_1SigmoidLayer.html',1,'cv::dnn']]],
  ['similarrects',['SimilarRects',['https://docs.opencv.org/3.4.1/d1/d65/classcv_1_1SimilarRects.html',1,'cv']]],
  ['simpleblobdetector',['SimpleBlobDetector',['https://docs.opencv.org/3.4.1/d0/d7a/classcv_1_1SimpleBlobDetector.html',1,'cv']]],
  ['simpledistance',['simpleDistance',['https://docs.opencv.org/3.4.1/d9/d12/structcvflann_1_1simpleDistance.html',1,'cvflann']]],
  ['simpledistance_3c_20chisquaredistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; ChiSquareDistance&lt; ElementType &gt;, ElementType &gt;',['https://docs.opencv.org/3.4.1/dd/d95/structcvflann_1_1simpleDistance_3_01ChiSquareDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20hellingerdistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; HellingerDistance&lt; ElementType &gt;, ElementType &gt;',['https://docs.opencv.org/3.4.1/db/d88/structcvflann_1_1simpleDistance_3_01HellingerDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20l2_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; L2&lt; ElementType &gt;, ElementType &gt;',['https://docs.opencv.org/3.4.1/dc/d3c/structcvflann_1_1simpleDistance_3_01L2_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20l2_5fsimple_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; L2_Simple&lt; ElementType &gt;, ElementType &gt;',['https://docs.opencv.org/3.4.1/d5/da0/structcvflann_1_1simpleDistance_3_01L2__Simple_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simpledistance_3c_20minkowskidistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['simpleDistance&lt; MinkowskiDistance&lt; ElementType &gt;, ElementType &gt;',['https://docs.opencv.org/3.4.1/db/dd1/structcvflann_1_1simpleDistance_3_01MinkowskiDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['simplewb',['SimpleWB',['https://docs.opencv.org/3.4.1/d1/d8b/classcv_1_1xphoto_1_1SimpleWB.html',1,'cv::xphoto']]],
  ['simulatedannealingsolversystem',['SimulatedAnnealingSolverSystem',['https://docs.opencv.org/3.4.1/dc/db4/structcv_1_1ml_1_1SimulatedAnnealingSolverSystem.html',1,'cv::ml']]],
  ['sin_5ffunc',['sin_func',['https://docs.opencv.org/3.4.1/d1/d05/structcv_1_1cudev_1_1sin__func.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20double_20_3e',['sin_func&lt; double &gt;',['https://docs.opencv.org/3.4.1/d8/d1c/structcv_1_1cudev_1_1sin__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20float_20_3e',['sin_func&lt; float &gt;',['https://docs.opencv.org/3.4.1/d6/d2b/structcv_1_1cudev_1_1sin__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20schar_20_3e',['sin_func&lt; schar &gt;',['https://docs.opencv.org/3.4.1/d8/d1b/structcv_1_1cudev_1_1sin__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20short_20_3e',['sin_func&lt; short &gt;',['https://docs.opencv.org/3.4.1/dd/d6f/structcv_1_1cudev_1_1sin__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20uchar_20_3e',['sin_func&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/d2/dfd/structcv_1_1cudev_1_1sin__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20uint_20_3e',['sin_func&lt; uint &gt;',['https://docs.opencv.org/3.4.1/d5/dbd/structcv_1_1cudev_1_1sin__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20ushort_20_3e',['sin_func&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/d8/d22/structcv_1_1cudev_1_1sin__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['singlemaskchannels',['SingleMaskChannels',['https://docs.opencv.org/3.4.1/db/dce/structcv_1_1cudev_1_1SingleMaskChannels.html',1,'cv::cudev']]],
  ['singlemaskchannelssz',['SingleMaskChannelsSz',['https://docs.opencv.org/3.4.1/d0/d19/structcv_1_1cudev_1_1SingleMaskChannelsSz.html',1,'cv::cudev']]],
  ['singlepolicy',['SinglePolicy',['https://docs.opencv.org/3.4.1/de/d31/classcvflann_1_1anyimpl_1_1SinglePolicy.html',1,'cvflann::anyimpl']]],
  ['sinh_5ffunc',['sinh_func',['https://docs.opencv.org/3.4.1/d8/da0/structcv_1_1cudev_1_1sinh__func.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20double_20_3e',['sinh_func&lt; double &gt;',['https://docs.opencv.org/3.4.1/db/dde/structcv_1_1cudev_1_1sinh__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20float_20_3e',['sinh_func&lt; float &gt;',['https://docs.opencv.org/3.4.1/d3/df1/structcv_1_1cudev_1_1sinh__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20schar_20_3e',['sinh_func&lt; schar &gt;',['https://docs.opencv.org/3.4.1/de/df6/structcv_1_1cudev_1_1sinh__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20short_20_3e',['sinh_func&lt; short &gt;',['https://docs.opencv.org/3.4.1/da/d3e/structcv_1_1cudev_1_1sinh__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20uchar_20_3e',['sinh_func&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/d4/dd2/structcv_1_1cudev_1_1sinh__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20uint_20_3e',['sinh_func&lt; uint &gt;',['https://docs.opencv.org/3.4.1/de/d13/structcv_1_1cudev_1_1sinh__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20ushort_20_3e',['sinh_func&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/d9/d38/structcv_1_1cudev_1_1sinh__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['sinusoidalpattern',['SinusoidalPattern',['https://docs.opencv.org/3.4.1/d6/d96/classcv_1_1structured__light_1_1SinusoidalPattern.html',1,'cv::structured_light']]],
  ['size_5f',['Size_',['https://docs.opencv.org/3.4.1/d6/d50/classcv_1_1Size__.html',1,'cv']]],
  ['size_5f_3c_20float_20_3e',['Size_&lt; float &gt;',['https://docs.opencv.org/3.4.1/d6/d50/classcv_1_1Size__.html',1,'cv::Size_&lt; float &gt;'],['https://docs.opencv.org/3.4.1/d6/d50/classcv_1_1Size__.html',1,'Size_&lt; float &gt;']]],
  ['size_5ft',['size_t',['http://en.cppreference.com/w/cpp/types/size_t.html',1,'std']]],
  ['skeleton',['skeleton',['https://docs.opencv.org/3.4.1/d4/d66/structcv_1_1datasets_1_1skeleton.html',1,'cv::datasets']]],
  ['sl2',['SL2',['https://docs.opencv.org/3.4.1/d5/d46/structcv_1_1SL2.html',1,'cv']]],
  ['slam_5fkitti',['SLAM_kitti',['https://docs.opencv.org/3.4.1/d6/d92/classcv_1_1datasets_1_1SLAM__kitti.html',1,'cv::datasets']]],
  ['slam_5fkittiobj',['SLAM_kittiObj',['https://docs.opencv.org/3.4.1/da/df4/structcv_1_1datasets_1_1SLAM__kittiObj.html',1,'cv::datasets']]],
  ['slam_5ftumindoor',['SLAM_tumindoor',['https://docs.opencv.org/3.4.1/da/d91/classcv_1_1datasets_1_1SLAM__tumindoor.html',1,'cv::datasets']]],
  ['slam_5ftumindoorobj',['SLAM_tumindoorObj',['https://docs.opencv.org/3.4.1/d7/d56/structcv_1_1datasets_1_1SLAM__tumindoorObj.html',1,'cv::datasets']]],
  ['slicelayer',['SliceLayer',['https://docs.opencv.org/3.4.1/de/d61/classcv_1_1dnn_1_1SliceLayer.html',1,'cv::dnn']]],
  ['small_5fany_5fpolicy',['small_any_policy',['https://docs.opencv.org/3.4.1/d7/d8e/structcvflann_1_1anyimpl_1_1small__any__policy.html',1,'cvflann::anyimpl']]],
  ['smatch',['smatch',['http://en.cppreference.com/w/cpp/regex/match_results.html',1,'std']]],
  ['sobelxptr',['SobelXPtr',['https://docs.opencv.org/3.4.1/de/dc8/structcv_1_1cudev_1_1SobelXPtr.html',1,'cv::cudev']]],
  ['sobelxptrsz',['SobelXPtrSz',['https://docs.opencv.org/3.4.1/d7/d84/structcv_1_1cudev_1_1SobelXPtrSz.html',1,'cv::cudev']]],
  ['sobelyptr',['SobelYPtr',['https://docs.opencv.org/3.4.1/d0/da6/structcv_1_1cudev_1_1SobelYPtr.html',1,'cv::cudev']]],
  ['sobelyptrsz',['SobelYPtrSz',['https://docs.opencv.org/3.4.1/dd/dc6/structcv_1_1cudev_1_1SobelYPtrSz.html',1,'cv::cudev']]],
  ['softdouble',['softdouble',['https://docs.opencv.org/3.4.1/de/df1/structcv_1_1softdouble.html',1,'cv']]],
  ['softfloat',['softfloat',['https://docs.opencv.org/3.4.1/d7/d2f/structcv_1_1softfloat.html',1,'cv']]],
  ['softmaxlayer',['SoftmaxLayer',['https://docs.opencv.org/3.4.1/d8/d18/classcv_1_1dnn_1_1SoftmaxLayer.html',1,'cv::dnn']]],
  ['sparsemat',['SparseMat',['https://docs.opencv.org/3.4.1/dd/da9/classcv_1_1SparseMat.html',1,'cv']]],
  ['sparsemat_5f',['SparseMat_',['https://docs.opencv.org/3.4.1/d7/d8a/classcv_1_1SparseMat__.html',1,'cv']]],
  ['sparsematchinterpolator',['SparseMatchInterpolator',['https://docs.opencv.org/3.4.1/d4/da8/classcv_1_1ximgproc_1_1SparseMatchInterpolator.html',1,'cv::ximgproc']]],
  ['sparsematconstiterator',['SparseMatConstIterator',['https://docs.opencv.org/3.4.1/df/dec/classcv_1_1SparseMatConstIterator.html',1,'cv']]],
  ['sparsematconstiterator_5f',['SparseMatConstIterator_',['https://docs.opencv.org/3.4.1/d9/d29/classcv_1_1SparseMatConstIterator__.html',1,'cv']]],
  ['sparsematiterator',['SparseMatIterator',['https://docs.opencv.org/3.4.1/d5/d9b/classcv_1_1SparseMatIterator.html',1,'cv']]],
  ['sparsematiterator_5f',['SparseMatIterator_',['https://docs.opencv.org/3.4.1/d3/d24/classcv_1_1SparseMatIterator__.html',1,'cv']]],
  ['sparseopticalflow',['SparseOpticalFlow',['https://docs.opencv.org/3.4.1/de/d14/classcv_1_1SparseOpticalFlow.html',1,'cv::SparseOpticalFlow'],['https://docs.opencv.org/3.4.1/d5/dcf/classcv_1_1cuda_1_1SparseOpticalFlow.html',1,'cv::cuda::SparseOpticalFlow']]],
  ['sparsepyrlkoptflowestimator',['SparsePyrLkOptFlowEstimator',['https://docs.opencv.org/3.4.1/d1/d4b/classcv_1_1videostab_1_1SparsePyrLkOptFlowEstimator.html',1,'cv::videostab']]],
  ['sparsepyrlkopticalflow',['SparsePyrLKOpticalFlow',['https://docs.opencv.org/3.4.1/d7/d08/classcv_1_1SparsePyrLKOpticalFlow.html',1,'cv::SparsePyrLKOpticalFlow'],['https://docs.opencv.org/3.4.1/d7/d05/classcv_1_1cuda_1_1SparsePyrLKOpticalFlow.html',1,'cv::cuda::SparsePyrLKOpticalFlow']]],
  ['sphericalportraitprojector',['SphericalPortraitProjector',['https://docs.opencv.org/3.4.1/d3/d0d/structcv_1_1detail_1_1SphericalPortraitProjector.html',1,'cv::detail']]],
  ['sphericalportraitwarper',['SphericalPortraitWarper',['https://docs.opencv.org/3.4.1/d8/d70/classcv_1_1detail_1_1SphericalPortraitWarper.html',1,'cv::detail']]],
  ['sphericalprojector',['SphericalProjector',['https://docs.opencv.org/3.4.1/d0/d88/structcv_1_1detail_1_1SphericalProjector.html',1,'cv::detail']]],
  ['sphericalwarper',['SphericalWarper',['https://docs.opencv.org/3.4.1/d3/d3c/classcv_1_1SphericalWarper.html',1,'cv::SphericalWarper'],['https://docs.opencv.org/3.4.1/d6/dd0/classcv_1_1detail_1_1SphericalWarper.html',1,'cv::detail::SphericalWarper']]],
  ['sphericalwarpergpu',['SphericalWarperGpu',['https://docs.opencv.org/3.4.1/db/d09/classcv_1_1detail_1_1SphericalWarperGpu.html',1,'cv::detail']]],
  ['split',['Split',['https://docs.opencv.org/3.4.1/d9/d37/classcv_1_1ml_1_1DTrees_1_1Split.html',1,'cv::ml::DTrees']]],
  ['splitlayer',['SplitLayer',['https://docs.opencv.org/3.4.1/dd/df9/classcv_1_1dnn_1_1SplitLayer.html',1,'cv::dnn']]],
  ['sqr_5ffunc',['sqr_func',['https://docs.opencv.org/3.4.1/d9/d1d/structcv_1_1cudev_1_1sqr__func.html',1,'cv::cudev']]],
  ['sqrt_5ffunc',['sqrt_func',['https://docs.opencv.org/3.4.1/d9/d47/structcv_1_1cudev_1_1sqrt__func.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20double_20_3e',['sqrt_func&lt; double &gt;',['https://docs.opencv.org/3.4.1/d4/d9d/structcv_1_1cudev_1_1sqrt__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20float_20_3e',['sqrt_func&lt; float &gt;',['https://docs.opencv.org/3.4.1/d8/dd2/structcv_1_1cudev_1_1sqrt__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20schar_20_3e',['sqrt_func&lt; schar &gt;',['https://docs.opencv.org/3.4.1/da/d64/structcv_1_1cudev_1_1sqrt__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20short_20_3e',['sqrt_func&lt; short &gt;',['https://docs.opencv.org/3.4.1/d2/d6a/structcv_1_1cudev_1_1sqrt__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20uchar_20_3e',['sqrt_func&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/d9/d33/structcv_1_1cudev_1_1sqrt__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20uint_20_3e',['sqrt_func&lt; uint &gt;',['https://docs.opencv.org/3.4.1/d0/d7b/structcv_1_1cudev_1_1sqrt__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20ushort_20_3e',['sqrt_func&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/df/df4/structcv_1_1cudev_1_1sqrt__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['squaredistance',['squareDistance',['https://docs.opencv.org/3.4.1/dc/d68/structcvflann_1_1squareDistance.html',1,'cvflann']]],
  ['squaredistance_3c_20chisquaredistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; ChiSquareDistance&lt; ElementType &gt;, ElementType &gt;',['https://docs.opencv.org/3.4.1/d2/deb/structcvflann_1_1squareDistance_3_01ChiSquareDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20hellingerdistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; HellingerDistance&lt; ElementType &gt;, ElementType &gt;',['https://docs.opencv.org/3.4.1/dc/d3f/structcvflann_1_1squareDistance_3_01HellingerDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20l2_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; L2&lt; ElementType &gt;, ElementType &gt;',['https://docs.opencv.org/3.4.1/d8/db8/structcvflann_1_1squareDistance_3_01L2_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20l2_5fsimple_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; L2_Simple&lt; ElementType &gt;, ElementType &gt;',['https://docs.opencv.org/3.4.1/d3/d86/structcvflann_1_1squareDistance_3_01L2__Simple_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['squaredistance_3c_20minkowskidistance_3c_20elementtype_20_3e_2c_20elementtype_20_3e',['squareDistance&lt; MinkowskiDistance&lt; ElementType &gt;, ElementType &gt;',['https://docs.opencv.org/3.4.1/dc/d73/structcvflann_1_1squareDistance_3_01MinkowskiDistance_3_01ElementType_01_4_00_01ElementType_01_4.html',1,'cvflann']]],
  ['sregex_5fiterator',['sregex_iterator',['http://en.cppreference.com/w/cpp/regex/regex_iterator.html',1,'std']]],
  ['sregex_5ftoken_5fiterator',['sregex_token_iterator',['http://en.cppreference.com/w/cpp/regex/regex_token_iterator.html',1,'std']]],
  ['ssub_5fmatch',['ssub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['stabilizerbase',['StabilizerBase',['https://docs.opencv.org/3.4.1/d2/d6c/classcv_1_1videostab_1_1StabilizerBase.html',1,'cv::videostab']]],
  ['stack',['stack',['http://en.cppreference.com/w/cpp/container/stack.html',1,'std']]],
  ['standardcollector',['StandardCollector',['https://docs.opencv.org/3.4.1/d4/d8d/classcv_1_1face_1_1StandardCollector.html',1,'cv::face']]],
  ['stardetector',['StarDetector',['https://docs.opencv.org/3.4.1/dd/d39/classcv_1_1xfeatures2d_1_1StarDetector.html',1,'cv::xfeatures2d']]],
  ['starkernelcensus',['StarKernelCensus',['https://docs.opencv.org/3.4.1/db/d3b/classcv_1_1stereo_1_1StarKernelCensus.html',1,'cv::stereo']]],
  ['startstoptimer',['StartStopTimer',['https://docs.opencv.org/3.4.1/de/dd0/classcvflann_1_1StartStopTimer.html',1,'cvflann']]],
  ['state_5ftype',['state_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf16::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_byname::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8_utf16::state_type']]],
  ['staticsaliency',['StaticSaliency',['https://docs.opencv.org/3.4.1/d5/d87/classcv_1_1saliency_1_1StaticSaliency.html',1,'cv::saliency']]],
  ['staticsaliencyfinegrained',['StaticSaliencyFineGrained',['https://docs.opencv.org/3.4.1/da/dd0/classcv_1_1saliency_1_1StaticSaliencyFineGrained.html',1,'cv::saliency']]],
  ['staticsaliencyspectralresidual',['StaticSaliencySpectralResidual',['https://docs.opencv.org/3.4.1/df/d37/classcv_1_1saliency_1_1StaticSaliencySpectralResidual.html',1,'cv::saliency']]],
  ['statmodel',['StatModel',['https://docs.opencv.org/3.4.1/db/d7d/classcv_1_1ml_1_1StatModel.html',1,'cv::ml']]],
  ['steady_5fclock',['steady_clock',['http://en.cppreference.com/w/cpp/chrono/steady_clock.html',1,'std::chrono']]],
  ['stereobeliefpropagation',['StereoBeliefPropagation',['https://docs.opencv.org/3.4.1/de/d7a/classcv_1_1cuda_1_1StereoBeliefPropagation.html',1,'cv::cuda']]],
  ['stereobinarybm',['StereoBinaryBM',['https://docs.opencv.org/3.4.1/d7/d8e/classcv_1_1stereo_1_1StereoBinaryBM.html',1,'cv::stereo']]],
  ['stereobinarysgbm',['StereoBinarySGBM',['https://docs.opencv.org/3.4.1/d1/d9f/classcv_1_1stereo_1_1StereoBinarySGBM.html',1,'cv::stereo']]],
  ['stereobm',['StereoBM',['https://docs.opencv.org/3.4.1/d9/dba/classcv_1_1StereoBM.html',1,'cv::StereoBM'],['https://docs.opencv.org/3.4.1/db/d8a/classcv_1_1cuda_1_1StereoBM.html',1,'cv::cuda::StereoBM']]],
  ['stereoconstantspacebp',['StereoConstantSpaceBP',['https://docs.opencv.org/3.4.1/d7/d09/classcv_1_1cuda_1_1StereoConstantSpaceBP.html',1,'cv::cuda']]],
  ['stereographicprojector',['StereographicProjector',['https://docs.opencv.org/3.4.1/d0/ddf/structcv_1_1detail_1_1StereographicProjector.html',1,'cv::detail']]],
  ['stereographicwarper',['StereographicWarper',['https://docs.opencv.org/3.4.1/d1/d3d/classcv_1_1detail_1_1StereographicWarper.html',1,'cv::detail::StereographicWarper'],['https://docs.opencv.org/3.4.1/d2/d5e/classcv_1_1StereographicWarper.html',1,'cv::StereographicWarper']]],
  ['stereomatcher',['StereoMatcher',['https://docs.opencv.org/3.4.1/d2/d6e/classcv_1_1StereoMatcher.html',1,'cv::StereoMatcher'],['https://docs.opencv.org/3.4.1/d9/d07/classcv_1_1stereo_1_1StereoMatcher.html',1,'cv::stereo::StereoMatcher']]],
  ['stereosgbm',['StereoSGBM',['https://docs.opencv.org/3.4.1/d2/d85/classcv_1_1StereoSGBM.html',1,'cv']]],
  ['stitcher',['Stitcher',['https://docs.opencv.org/3.4.1/d2/d8d/classcv_1_1Stitcher.html',1,'cv']]],
  ['stream',['Stream',['https://docs.opencv.org/3.4.1/d9/df3/classcv_1_1cuda_1_1Stream.html',1,'cv::cuda']]],
  ['streamaccessor',['StreamAccessor',['https://docs.opencv.org/3.4.1/d6/df1/structcv_1_1cuda_1_1StreamAccessor.html',1,'cv::cuda']]],
  ['streambuf',['streambuf',['http://en.cppreference.com/w/cpp/io/basic_streambuf.html',1,'std']]],
  ['streamoff',['streamoff',['http://en.cppreference.com/w/cpp/io/streamoff.html',1,'std']]],
  ['streampos',['streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['streamsize',['streamsize',['http://en.cppreference.com/w/cpp/io/streamsize.html',1,'std']]],
  ['string',['string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std::string'],['https://docs.opencv.org/3.4.1/d1/d8f/classcv_1_1String.html',1,'cv::String']]],
  ['string_5ftype',['string_type',['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct::string_type'],['http://en.cppreference.com/w/cpp/locale/money_put.html',1,'std::money_put::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate::string_type'],['http://en.cppreference.com/w/cpp/locale/money_get.html',1,'std::money_get::string_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct_byname::string_type']]],
  ['stringbuf',['stringbuf',['http://en.cppreference.com/w/cpp/io/basic_stringbuf.html',1,'std']]],
  ['stringstream',['stringstream',['http://en.cppreference.com/w/cpp/io/basic_stringstream.html',1,'std']]],
  ['strongclassifierdirectselection',['StrongClassifierDirectSelection',['https://docs.opencv.org/3.4.1/d4/d1e/classcv_1_1StrongClassifierDirectSelection.html',1,'cv']]],
  ['strstream',['strstream',['http://en.cppreference.com/w/cpp/io/strstream.html',1,'std']]],
  ['strstreambuf',['strstreambuf',['http://en.cppreference.com/w/cpp/io/strstreambuf.html',1,'std']]],
  ['structurededgedetection',['StructuredEdgeDetection',['https://docs.opencv.org/3.4.1/d8/d54/classcv_1_1ximgproc_1_1StructuredEdgeDetection.html',1,'cv::ximgproc']]],
  ['structuredlightpattern',['StructuredLightPattern',['https://docs.opencv.org/3.4.1/d9/dbb/classcv_1_1structured__light_1_1StructuredLightPattern.html',1,'cv::structured_light']]],
  ['student_5ft_5fdistribution',['student_t_distribution',['http://en.cppreference.com/w/cpp/numeric/random/student_t_distribution.html',1,'std']]],
  ['sub_5fmatch',['sub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['subdiv2d',['Subdiv2D',['https://docs.opencv.org/3.4.1/df/dbf/classcv_1_1Subdiv2D.html',1,'cv']]],
  ['subtract_5fwith_5fcarry_5fengine',['subtract_with_carry_engine',['http://en.cppreference.com/w/cpp/numeric/random/subtract_with_carry_engine.html',1,'std']]],
  ['sum',['Sum',['https://docs.opencv.org/3.4.1/d8/d60/structcv_1_1cudev_1_1Sum.html',1,'cv::cudev']]],
  ['sumexprbody',['SumExprBody',['https://docs.opencv.org/3.4.1/dd/d33/structcv_1_1cudev_1_1SumExprBody.html',1,'cv::cudev']]],
  ['superpixellsc',['SuperpixelLSC',['https://docs.opencv.org/3.4.1/d5/da0/classcv_1_1ximgproc_1_1SuperpixelLSC.html',1,'cv::ximgproc']]],
  ['superpixelseeds',['SuperpixelSEEDS',['https://docs.opencv.org/3.4.1/df/d81/classcv_1_1ximgproc_1_1SuperpixelSEEDS.html',1,'cv::ximgproc']]],
  ['superpixelslic',['SuperpixelSLIC',['https://docs.opencv.org/3.4.1/d3/da9/classcv_1_1ximgproc_1_1SuperpixelSLIC.html',1,'cv::ximgproc']]],
  ['superresolution',['SuperResolution',['https://docs.opencv.org/3.4.1/d9/dd6/classcv_1_1superres_1_1SuperResolution.html',1,'cv::superres']]],
  ['surf',['SURF',['https://docs.opencv.org/3.4.1/d5/df7/classcv_1_1xfeatures2d_1_1SURF.html',1,'cv::xfeatures2d']]],
  ['surf_5fcuda',['SURF_CUDA',['https://docs.opencv.org/3.4.1/db/d06/classcv_1_1cuda_1_1SURF__CUDA.html',1,'cv::cuda']]],
  ['surffeaturesfinder',['SurfFeaturesFinder',['https://docs.opencv.org/3.4.1/df/d27/classcv_1_1detail_1_1SurfFeaturesFinder.html',1,'cv::detail']]],
  ['svd',['SVD',['https://docs.opencv.org/3.4.1/df/df7/classcv_1_1SVD.html',1,'cv']]],
  ['svm',['SVM',['https://docs.opencv.org/3.4.1/d1/d2d/classcv_1_1ml_1_1SVM.html',1,'cv::ml']]],
  ['svmsgd',['SVMSGD',['https://docs.opencv.org/3.4.1/de/d54/classcv_1_1ml_1_1SVMSGD.html',1,'cv::ml']]],
  ['symetriccensus',['SymetricCensus',['https://docs.opencv.org/3.4.1/dd/d24/classcv_1_1stereo_1_1SymetricCensus.html',1,'cv::stereo']]],
  ['syntheticsequencegenerator',['SyntheticSequenceGenerator',['https://docs.opencv.org/3.4.1/d1/dda/classcv_1_1bgsegm_1_1SyntheticSequenceGenerator.html',1,'cv::bgsegm']]],
  ['system_5fclock',['system_clock',['http://en.cppreference.com/w/cpp/chrono/system_clock.html',1,'std::chrono']]],
  ['system_5ferror',['system_error',['http://en.cppreference.com/w/cpp/error/system_error.html',1,'std']]]
];
