var searchData=
[
  ['edge',['edge',['https://docs.opencv.org/3.4.1/df/db0/structcv_1_1multicalib_1_1MultiCameraCalibration_1_1edge.html',1,'cv::multicalib::MultiCameraCalibration']]],
  ['edgeawareinterpolator',['EdgeAwareInterpolator',['https://docs.opencv.org/3.4.1/d4/dfa/classcv_1_1ximgproc_1_1EdgeAwareInterpolator.html',1,'cv::ximgproc']]],
  ['edgeboxes',['EdgeBoxes',['https://docs.opencv.org/3.4.1/dd/d65/classcv_1_1ximgproc_1_1EdgeBoxes.html',1,'cv::ximgproc']]],
  ['eigenfacerecognizer',['EigenFaceRecognizer',['https://docs.opencv.org/3.4.1/dd/d7c/classcv_1_1face_1_1EigenFaceRecognizer.html',1,'cv::face']]],
  ['elliptic_5fkeypoint',['Elliptic_KeyPoint',['https://docs.opencv.org/3.4.1/d2/d71/classcv_1_1xfeatures2d_1_1Elliptic__KeyPoint.html',1,'cv::xfeatures2d']]],
  ['eltwiselayer',['EltwiseLayer',['https://docs.opencv.org/3.4.1/d6/d6a/classcv_1_1dnn_1_1EltwiseLayer.html',1,'cv::dnn']]],
  ['elulayer',['ELULayer',['https://docs.opencv.org/3.4.1/df/da5/classcv_1_1dnn_1_1ELULayer.html',1,'cv::dnn']]],
  ['em',['EM',['https://docs.opencv.org/3.4.1/d1/dfb/classcv_1_1ml_1_1EM.html',1,'cv::ml']]],
  ['emdhistogramcostextractor',['EMDHistogramCostExtractor',['https://docs.opencv.org/3.4.1/d0/d1c/classcv_1_1EMDHistogramCostExtractor.html',1,'cv']]],
  ['emdl1histogramcostextractor',['EMDL1HistogramCostExtractor',['https://docs.opencv.org/3.4.1/da/d8e/classcv_1_1EMDL1HistogramCostExtractor.html',1,'cv']]],
  ['empty_5fany',['empty_any',['https://docs.opencv.org/3.4.1/d5/d44/structcvflann_1_1anyimpl_1_1empty__any.html',1,'cvflann::anyimpl']]],
  ['enable_5fif',['enable_if',['http://en.cppreference.com/w/cpp/types/enable_if.html',1,'std']]],
  ['enable_5fshared_5ffrom_5fthis',['enable_shared_from_this',['http://en.cppreference.com/w/cpp/memory/enable_shared_from_this.html',1,'std']]],
  ['enableif',['EnableIf',['https://docs.opencv.org/3.4.1/dd/d8b/structcv_1_1cudev_1_1EnableIf.html',1,'cv::cudev']]],
  ['enableif_3c_20true_2c_20t_20_3e',['EnableIf&lt; true, T &gt;',['https://docs.opencv.org/3.4.1/dd/dda/structcv_1_1cudev_1_1EnableIf_3_01true_00_01T_01_4.html',1,'cv::cudev']]],
  ['encodercallback',['EncoderCallBack',['https://docs.opencv.org/3.4.1/d6/db6/classcv_1_1cudacodec_1_1EncoderCallBack.html',1,'cv::cudacodec']]],
  ['encoderparams',['EncoderParams',['https://docs.opencv.org/3.4.1/d3/db6/structcv_1_1cudacodec_1_1EncoderParams.html',1,'cv::cudacodec']]],
  ['equal_5fto',['equal_to',['https://docs.opencv.org/3.4.1/d2/dfd/structcv_1_1cudev_1_1equal__to.html',1,'cv::cudev::equal_to&lt; class &gt;'],['http://en.cppreference.com/w/cpp/utility/functional/equal_to.html',1,'std::equal_to']]],
  ['erfilter',['ERFilter',['https://docs.opencv.org/3.4.1/da/def/classcv_1_1text_1_1ERFilter.html',1,'cv::text']]],
  ['errc',['errc',['http://en.cppreference.com/w/cpp/error/errc.html',1,'std']]],
  ['error_5fcategory',['error_category',['http://en.cppreference.com/w/cpp/error/error_category.html',1,'std']]],
  ['error_5fcode',['error_code',['http://en.cppreference.com/w/cpp/error/error_code.html',1,'std']]],
  ['error_5fcondition',['error_condition',['http://en.cppreference.com/w/cpp/error/error_condition.html',1,'std']]],
  ['erstat',['ERStat',['https://docs.opencv.org/3.4.1/db/d20/structcv_1_1text_1_1ERStat.html',1,'cv::text']]],
  ['estimatedgaussdistribution',['EstimatedGaussDistribution',['https://docs.opencv.org/3.4.1/d3/d24/classcv_1_1EstimatedGaussDistribution.html',1,'cv']]],
  ['estimator',['Estimator',['https://docs.opencv.org/3.4.1/df/d15/classcv_1_1detail_1_1Estimator.html',1,'cv::detail']]],
  ['event',['Event',['https://docs.opencv.org/3.4.1/d5/d38/classcv_1_1cuda_1_1Event.html',1,'cv::cuda']]],
  ['event_5fcallback',['event_callback',['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::basic_ofstream&lt; Char &gt;::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::fstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::wostream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::basic_ostringstream&lt; Char &gt;::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::basic_ios&lt; Char &gt;::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::ostringstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::basic_fstream&lt; Char &gt;::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::iostream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::ios_base::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::wistream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::stringstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::ostream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::wifstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::basic_istream&lt; Char &gt;::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::strstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::basic_stringstream&lt; Char &gt;::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::wostringstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::istrstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::basic_ostream&lt; Char &gt;::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::wiostream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::ofstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::basic_istringstream&lt; Char &gt;::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::basic_ifstream&lt; Char &gt;::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::istringstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::istream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::ostrstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::wfstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::basic_iostream&lt; Char &gt;::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::wofstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::wstringstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::wistringstream::event_callback'],['http://en.cppreference.com/w/cpp/io/ios_base/event_callback.html',1,'std::ifstream::event_callback']]],
  ['eventaccessor',['EventAccessor',['https://docs.opencv.org/3.4.1/da/d71/structcv_1_1cuda_1_1EventAccessor.html',1,'cv::cuda']]],
  ['exa',['exa',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['exception',['Exception',['https://docs.opencv.org/3.4.1/d1/dee/classcv_1_1Exception.html',1,'cv::Exception'],['http://en.cppreference.com/w/cpp/error/exception.html',1,'std::exception']]],
  ['exception_5fptr',['exception_ptr',['http://en.cppreference.com/w/cpp/error/exception_ptr.html',1,'std']]],
  ['exp10_5ffunc',['exp10_func',['https://docs.opencv.org/3.4.1/dc/d8b/structcv_1_1cudev_1_1exp10__func.html',1,'cv::cudev']]],
  ['exp10_5ffunc_3c_20double_20_3e',['exp10_func&lt; double &gt;',['https://docs.opencv.org/3.4.1/d0/d66/structcv_1_1cudev_1_1exp10__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['exp10_5ffunc_3c_20float_20_3e',['exp10_func&lt; float &gt;',['https://docs.opencv.org/3.4.1/d4/d78/structcv_1_1cudev_1_1exp10__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['exp10_5ffunc_3c_20schar_20_3e',['exp10_func&lt; schar &gt;',['https://docs.opencv.org/3.4.1/d6/dde/structcv_1_1cudev_1_1exp10__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['exp10_5ffunc_3c_20short_20_3e',['exp10_func&lt; short &gt;',['https://docs.opencv.org/3.4.1/d7/d59/structcv_1_1cudev_1_1exp10__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['exp10_5ffunc_3c_20uchar_20_3e',['exp10_func&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/d1/ddd/structcv_1_1cudev_1_1exp10__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['exp10_5ffunc_3c_20uint_20_3e',['exp10_func&lt; uint &gt;',['https://docs.opencv.org/3.4.1/d5/dc3/structcv_1_1cudev_1_1exp10__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['exp10_5ffunc_3c_20ushort_20_3e',['exp10_func&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/d4/da4/structcv_1_1cudev_1_1exp10__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['exp2_5ffunc',['exp2_func',['https://docs.opencv.org/3.4.1/dc/dd9/structcv_1_1cudev_1_1exp2__func.html',1,'cv::cudev']]],
  ['exp2_5ffunc_3c_20double_20_3e',['exp2_func&lt; double &gt;',['https://docs.opencv.org/3.4.1/d8/d9b/structcv_1_1cudev_1_1exp2__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['exp2_5ffunc_3c_20float_20_3e',['exp2_func&lt; float &gt;',['https://docs.opencv.org/3.4.1/d8/dc7/structcv_1_1cudev_1_1exp2__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['exp2_5ffunc_3c_20schar_20_3e',['exp2_func&lt; schar &gt;',['https://docs.opencv.org/3.4.1/de/da5/structcv_1_1cudev_1_1exp2__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['exp2_5ffunc_3c_20short_20_3e',['exp2_func&lt; short &gt;',['https://docs.opencv.org/3.4.1/da/d29/structcv_1_1cudev_1_1exp2__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['exp2_5ffunc_3c_20uchar_20_3e',['exp2_func&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/d2/d8b/structcv_1_1cudev_1_1exp2__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['exp2_5ffunc_3c_20uint_20_3e',['exp2_func&lt; uint &gt;',['https://docs.opencv.org/3.4.1/dc/dd4/structcv_1_1cudev_1_1exp2__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['exp2_5ffunc_3c_20ushort_20_3e',['exp2_func&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/d9/d30/structcv_1_1cudev_1_1exp2__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['exp_5ffunc',['exp_func',['https://docs.opencv.org/3.4.1/dc/d73/structcv_1_1cudev_1_1exp__func.html',1,'cv::cudev']]],
  ['exp_5ffunc_3c_20double_20_3e',['exp_func&lt; double &gt;',['https://docs.opencv.org/3.4.1/dd/db1/structcv_1_1cudev_1_1exp__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['exp_5ffunc_3c_20float_20_3e',['exp_func&lt; float &gt;',['https://docs.opencv.org/3.4.1/df/dba/structcv_1_1cudev_1_1exp__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['exp_5ffunc_3c_20schar_20_3e',['exp_func&lt; schar &gt;',['https://docs.opencv.org/3.4.1/d1/d33/structcv_1_1cudev_1_1exp__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['exp_5ffunc_3c_20short_20_3e',['exp_func&lt; short &gt;',['https://docs.opencv.org/3.4.1/d7/d67/structcv_1_1cudev_1_1exp__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['exp_5ffunc_3c_20uchar_20_3e',['exp_func&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/d9/de4/structcv_1_1cudev_1_1exp__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['exp_5ffunc_3c_20uint_20_3e',['exp_func&lt; uint &gt;',['https://docs.opencv.org/3.4.1/d3/d6c/structcv_1_1cudev_1_1exp__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['exp_5ffunc_3c_20ushort_20_3e',['exp_func&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/d6/dde/structcv_1_1cudev_1_1exp__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['exponential_5fdistribution',['exponential_distribution',['http://en.cppreference.com/w/cpp/numeric/random/exponential_distribution.html',1,'std']]],
  ['exposurecompensator',['ExposureCompensator',['https://docs.opencv.org/3.4.1/d2/d37/classcv_1_1detail_1_1ExposureCompensator.html',1,'cv::detail']]],
  ['expr',['Expr',['https://docs.opencv.org/3.4.1/de/dfb/structcv_1_1cudev_1_1Expr.html',1,'cv::cudev']]],
  ['extent',['extent',['http://en.cppreference.com/w/cpp/types/extent.html',1,'std']]],
  ['extern_5ftype',['extern_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt::extern_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_byname::extern_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8::extern_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8_utf16::extern_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf16::extern_type']]],
  ['extreme_5fvalue_5fdistribution',['extreme_value_distribution',['http://en.cppreference.com/w/cpp/numeric/random/extreme_value_distribution.html',1,'std']]]
];
