var searchData=
[
  ['v_5freg',['v_reg',['https://docs.opencv.org/3.4.1/d1/d69/structcv_1_1v__reg.html',1,'cv']]],
  ['va_5flist',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['value_5fcompare',['value_compare',['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap&lt; K, T &gt;::value_compare'],['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map&lt; K, T &gt;::value_compare']]],
  ['variationalrefinement',['VariationalRefinement',['https://docs.opencv.org/3.4.1/d8/dcc/classcv_1_1optflow_1_1VariationalRefinement.html',1,'cv::optflow']]],
  ['vec',['Vec',['https://docs.opencv.org/3.4.1/d6/dcf/classcv_1_1Vec.html',1,'cv']]],
  ['vec_3c_20_5ftp_2c_204_20_3e',['Vec&lt; _Tp, 4 &gt;',['https://docs.opencv.org/3.4.1/d6/dcf/classcv_1_1Vec.html',1,'']]],
  ['vec_3c_20double_2c_202_20_3e',['Vec&lt; double, 2 &gt;',['https://docs.opencv.org/3.4.1/d6/dcf/classcv_1_1Vec.html',1,'']]],
  ['vec_3c_20double_2c_203_20_3e',['Vec&lt; double, 3 &gt;',['https://docs.opencv.org/3.4.1/d6/dcf/classcv_1_1Vec.html',1,'Vec&lt; double, 3 &gt;'],['https://docs.opencv.org/3.4.1/d6/dcf/classcv_1_1Vec.html',1,'cv::Vec&lt; double, 3 &gt;']]],
  ['vec_3c_20double_2c_204_20_3e',['Vec&lt; double, 4 &gt;',['https://docs.opencv.org/3.4.1/d6/dcf/classcv_1_1Vec.html',1,'Vec&lt; double, 4 &gt;'],['https://docs.opencv.org/3.4.1/d6/dcf/classcv_1_1Vec.html',1,'cv::Vec&lt; double, 4 &gt;']]],
  ['vec_3c_20double_2c_20cv_3a_3aoptflow_3a_3agpcpatchdescriptor_3a_3anfeatures_20_3e',['Vec&lt; double, cv::optflow::GPCPatchDescriptor::nFeatures &gt;',['https://docs.opencv.org/3.4.1/d6/dcf/classcv_1_1Vec.html',1,'']]],
  ['vec_3c_20double_2c_20gpcpatchdescriptor_3a_3anfeatures_20_3e',['Vec&lt; double, GPCPatchDescriptor::nFeatures &gt;',['https://docs.opencv.org/3.4.1/d6/dcf/classcv_1_1Vec.html',1,'cv']]],
  ['vec_3c_20double_2c_20nfeatures_20_3e',['Vec&lt; double, nFeatures &gt;',['https://docs.opencv.org/3.4.1/d6/dcf/classcv_1_1Vec.html',1,'Vec&lt; double, nFeatures &gt;'],['https://docs.opencv.org/3.4.1/d6/dcf/classcv_1_1Vec.html',1,'cv::Vec&lt; double, nFeatures &gt;']]],
  ['veccommainitializer',['VecCommaInitializer',['https://docs.opencv.org/3.4.1/d1/d3e/classcv_1_1VecCommaInitializer.html',1,'cv']]],
  ['vector',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20char_20_3e',['vector&lt; char &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3acvhaarevaluator_3a_3afeaturehaar_20_3e',['vector&lt; cv::CvHaarEvaluator::FeatureHaar &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3acvhogevaluator_3a_3afeature_20_3e',['vector&lt; cv::CvHOGEvaluator::Feature &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3acvlbpevaluator_3a_3afeature_20_3e',['vector&lt; cv::CvLBPEvaluator::Feature &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3adatasets_3a_3acamerapos_20_3e',['vector&lt; cv::datasets::cameraPos &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3adatasets_3a_3agroundtruth_20_3e',['vector&lt; cv::datasets::groundTruth &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3adatasets_3a_3apascalobj_20_3e',['vector&lt; cv::datasets::PascalObj &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3adatasets_3a_3apascalpart_20_3e',['vector&lt; cv::datasets::PascalPart &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3adatasets_3a_3apose_20_3e',['vector&lt; cv::datasets::pose &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3adatasets_3a_3askeleton_20_3e',['vector&lt; cv::datasets::skeleton &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3adatasets_3a_3atag_20_3e',['vector&lt; cv::datasets::tag &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3adatasets_3a_3aword_20_3e',['vector&lt; cv::datasets::word &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3admatch_20_3e',['vector&lt; cv::DMatch &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3adnn_5fobjdetect_3a_3aobject_20_3e',['vector&lt; cv::dnn_objdetect::object &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3aface_3a_3afacemarkaam_3a_3amodel_3a_3atexture_20_3e',['vector&lt; cv::face::FacemarkAAM::Model::Texture &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3akeypoint_20_3e',['vector&lt; cv::KeyPoint &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3alinemod_3a_3afeature_20_3e',['vector&lt; cv::linemod::Feature &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3amat_20_3e',['vector&lt; cv::Mat &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3anode_3c_20object_20_3e_20_2a_20_3e',['vector&lt; cv::Node&lt; OBJECT &gt; * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3apoint3_5f_20_3e',['vector&lt; cv::Point3_ &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3aptr_20_3e',['vector&lt; cv::Ptr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3aptr_3c_20cv_3a_3alinemod_3a_3amodality_20_3e_20_3e',['vector&lt; cv::Ptr&lt; cv::linemod::Modality &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3aptr_3c_20cv_3a_3atracker_20_3e_20_3e',['vector&lt; cv::Ptr&lt; cv::Tracker &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3arect_5f_20_3e',['vector&lt; cv::Rect_ &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3asize_5f_20_3e',['vector&lt; cv::Size_ &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3asubdiv2d_3a_3avertex_20_3e',['vector&lt; cv::Subdiv2D::Vertex &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3aumat_20_3e',['vector&lt; cv::UMat &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cv_3a_3avec_20_3e',['vector&lt; cv::Vec &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20double_20_3e',['vector&lt; double &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20float_20_3e',['vector&lt; float &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20int_20_3e',['vector&lt; int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20point_5f_3c_20float_20_3e_20_3e',['vector&lt; Point_&lt; float &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20point_5f_3c_20int_20_3e_20_3e',['vector&lt; Point_&lt; int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20predictresult_20_3e',['vector&lt; PredictResult &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20ptr_3c_20trackertargetstate_20_3e_20_3e',['vector&lt; Ptr&lt; TrackerTargetState &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20quadedge_20_3e',['vector&lt; QuadEdge &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20scalar_5f_3c_20double_20_3e_20_3e',['vector&lt; Scalar_&lt; double &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20size_5ft_20_3e',['vector&lt; size_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3apair_3c_20int_2c_20int_20_3e_20_3e',['vector&lt; std::pair&lt; int, int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3apair_3c_20ptr_3c_20trackertargetstate_20_3e_2c_20float_20_3e_20_3e',['vector&lt; std::pair&lt; Ptr&lt; TrackerTargetState &gt;, float &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3astring_20_3e',['vector&lt; std::string &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_20_3e',['vector&lt; std::vector &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20cv_3a_3apoint3_5f_20_3e_20_3e',['vector&lt; std::vector&lt; cv::Point3_ &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20cv_3a_3aptr_3c_20cv_3a_3adatasets_3a_3aobject_20_3e_20_3e_20_3e',['vector&lt; std::vector&lt; cv::Ptr&lt; cv::datasets::Object &gt; &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20cv_3a_3arange_20_3e_20_3e',['vector&lt; std::vector&lt; cv::Range &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20int_20_3e_20_3e',['vector&lt; std::vector&lt; int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20point_5f_3c_20int_20_3e_20_3e_20_3e',['vector&lt; std::vector&lt; Point_&lt; int &gt; &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3avector_3c_20unsigned_20int_20_3e_20_3e',['vector&lt; std::vector&lt; unsigned int &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20templatepyramid_20_3e',['vector&lt; TemplatePyramid &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20uchar_20_3e',['vector&lt; uchar &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20unsigned_20int_20_3e',['vector&lt; unsigned int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vectraits',['VecTraits',['https://docs.opencv.org/3.4.1/d6/d77/structcv_1_1cudev_1_1VecTraits.html',1,'cv::cudev']]],
  ['vectraits_3c_20char1_20_3e',['VecTraits&lt; char1 &gt;',['https://docs.opencv.org/3.4.1/dc/df8/structcv_1_1cudev_1_1VecTraits_3_01char1_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20char2_20_3e',['VecTraits&lt; char2 &gt;',['https://docs.opencv.org/3.4.1/d0/d8d/structcv_1_1cudev_1_1VecTraits_3_01char2_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20char3_20_3e',['VecTraits&lt; char3 &gt;',['https://docs.opencv.org/3.4.1/df/de4/structcv_1_1cudev_1_1VecTraits_3_01char3_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20char4_20_3e',['VecTraits&lt; char4 &gt;',['https://docs.opencv.org/3.4.1/dc/df6/structcv_1_1cudev_1_1VecTraits_3_01char4_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20double_20_3e',['VecTraits&lt; double &gt;',['https://docs.opencv.org/3.4.1/d1/d4e/structcv_1_1cudev_1_1VecTraits_3_01double_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20double1_20_3e',['VecTraits&lt; double1 &gt;',['https://docs.opencv.org/3.4.1/d1/de1/structcv_1_1cudev_1_1VecTraits_3_01double1_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20double2_20_3e',['VecTraits&lt; double2 &gt;',['https://docs.opencv.org/3.4.1/d6/ded/structcv_1_1cudev_1_1VecTraits_3_01double2_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20double3_20_3e',['VecTraits&lt; double3 &gt;',['https://docs.opencv.org/3.4.1/d5/d24/structcv_1_1cudev_1_1VecTraits_3_01double3_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20double4_20_3e',['VecTraits&lt; double4 &gt;',['https://docs.opencv.org/3.4.1/d1/d5d/structcv_1_1cudev_1_1VecTraits_3_01double4_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20float_20_3e',['VecTraits&lt; float &gt;',['https://docs.opencv.org/3.4.1/d0/d48/structcv_1_1cudev_1_1VecTraits_3_01float_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20float1_20_3e',['VecTraits&lt; float1 &gt;',['https://docs.opencv.org/3.4.1/dc/d22/structcv_1_1cudev_1_1VecTraits_3_01float1_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20float2_20_3e',['VecTraits&lt; float2 &gt;',['https://docs.opencv.org/3.4.1/d9/dfe/structcv_1_1cudev_1_1VecTraits_3_01float2_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20float3_20_3e',['VecTraits&lt; float3 &gt;',['https://docs.opencv.org/3.4.1/d9/d1a/structcv_1_1cudev_1_1VecTraits_3_01float3_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20float4_20_3e',['VecTraits&lt; float4 &gt;',['https://docs.opencv.org/3.4.1/d9/d9c/structcv_1_1cudev_1_1VecTraits_3_01float4_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20int1_20_3e',['VecTraits&lt; int1 &gt;',['https://docs.opencv.org/3.4.1/d7/dc2/structcv_1_1cudev_1_1VecTraits_3_01int1_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20int2_20_3e',['VecTraits&lt; int2 &gt;',['https://docs.opencv.org/3.4.1/de/de4/structcv_1_1cudev_1_1VecTraits_3_01int2_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20int3_20_3e',['VecTraits&lt; int3 &gt;',['https://docs.opencv.org/3.4.1/d5/dee/structcv_1_1cudev_1_1VecTraits_3_01int3_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20int4_20_3e',['VecTraits&lt; int4 &gt;',['https://docs.opencv.org/3.4.1/da/d75/structcv_1_1cudev_1_1VecTraits_3_01int4_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20schar_20_3e',['VecTraits&lt; schar &gt;',['https://docs.opencv.org/3.4.1/d4/d43/structcv_1_1cudev_1_1VecTraits_3_01schar_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20short_20_3e',['VecTraits&lt; short &gt;',['https://docs.opencv.org/3.4.1/da/df0/structcv_1_1cudev_1_1VecTraits_3_01short_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20short1_20_3e',['VecTraits&lt; short1 &gt;',['https://docs.opencv.org/3.4.1/d6/dec/structcv_1_1cudev_1_1VecTraits_3_01short1_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20short2_20_3e',['VecTraits&lt; short2 &gt;',['https://docs.opencv.org/3.4.1/dd/d78/structcv_1_1cudev_1_1VecTraits_3_01short2_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20short3_20_3e',['VecTraits&lt; short3 &gt;',['https://docs.opencv.org/3.4.1/da/d6d/structcv_1_1cudev_1_1VecTraits_3_01short3_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20short4_20_3e',['VecTraits&lt; short4 &gt;',['https://docs.opencv.org/3.4.1/d7/d59/structcv_1_1cudev_1_1VecTraits_3_01short4_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20uchar_20_3e',['VecTraits&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/df/d87/structcv_1_1cudev_1_1VecTraits_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20uchar1_20_3e',['VecTraits&lt; uchar1 &gt;',['https://docs.opencv.org/3.4.1/db/d87/structcv_1_1cudev_1_1VecTraits_3_01uchar1_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20uchar2_20_3e',['VecTraits&lt; uchar2 &gt;',['https://docs.opencv.org/3.4.1/d0/da8/structcv_1_1cudev_1_1VecTraits_3_01uchar2_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20uchar3_20_3e',['VecTraits&lt; uchar3 &gt;',['https://docs.opencv.org/3.4.1/da/d8a/structcv_1_1cudev_1_1VecTraits_3_01uchar3_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20uchar4_20_3e',['VecTraits&lt; uchar4 &gt;',['https://docs.opencv.org/3.4.1/d4/dc1/structcv_1_1cudev_1_1VecTraits_3_01uchar4_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20uint_20_3e',['VecTraits&lt; uint &gt;',['https://docs.opencv.org/3.4.1/de/d87/structcv_1_1cudev_1_1VecTraits_3_01uint_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20uint1_20_3e',['VecTraits&lt; uint1 &gt;',['https://docs.opencv.org/3.4.1/de/d41/structcv_1_1cudev_1_1VecTraits_3_01uint1_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20uint2_20_3e',['VecTraits&lt; uint2 &gt;',['https://docs.opencv.org/3.4.1/d7/d19/structcv_1_1cudev_1_1VecTraits_3_01uint2_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20uint3_20_3e',['VecTraits&lt; uint3 &gt;',['https://docs.opencv.org/3.4.1/da/d00/structcv_1_1cudev_1_1VecTraits_3_01uint3_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20uint4_20_3e',['VecTraits&lt; uint4 &gt;',['https://docs.opencv.org/3.4.1/dc/d7c/structcv_1_1cudev_1_1VecTraits_3_01uint4_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20ushort_20_3e',['VecTraits&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/d9/db8/structcv_1_1cudev_1_1VecTraits_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20ushort1_20_3e',['VecTraits&lt; ushort1 &gt;',['https://docs.opencv.org/3.4.1/da/d76/structcv_1_1cudev_1_1VecTraits_3_01ushort1_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20ushort2_20_3e',['VecTraits&lt; ushort2 &gt;',['https://docs.opencv.org/3.4.1/d0/d40/structcv_1_1cudev_1_1VecTraits_3_01ushort2_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20ushort3_20_3e',['VecTraits&lt; ushort3 &gt;',['https://docs.opencv.org/3.4.1/d4/dd7/structcv_1_1cudev_1_1VecTraits_3_01ushort3_01_4.html',1,'cv::cudev']]],
  ['vectraits_3c_20ushort4_20_3e',['VecTraits&lt; ushort4 &gt;',['https://docs.opencv.org/3.4.1/d3/d14/structcv_1_1cudev_1_1VecTraits_3_01ushort4_01_4.html',1,'cv::cudev']]],
  ['vertex',['vertex',['https://docs.opencv.org/3.4.1/d1/db5/structcv_1_1multicalib_1_1MultiCameraCalibration_1_1vertex.html',1,'cv::multicalib::MultiCameraCalibration::vertex'],['https://docs.opencv.org/3.4.1/d7/de9/structcv_1_1Subdiv2D_1_1Vertex.html',1,'cv::Subdiv2D::Vertex']]],
  ['vgg',['VGG',['https://docs.opencv.org/3.4.1/d6/d00/classcv_1_1xfeatures2d_1_1VGG.html',1,'cv::xfeatures2d']]],
  ['videocapture',['VideoCapture',['https://docs.opencv.org/3.4.1/d8/dfe/classcv_1_1VideoCapture.html',1,'cv']]],
  ['videofilesource',['VideoFileSource',['https://docs.opencv.org/3.4.1/da/d0b/classcv_1_1videostab_1_1VideoFileSource.html',1,'cv::videostab']]],
  ['videoreader',['VideoReader',['https://docs.opencv.org/3.4.1/db/ded/classcv_1_1cudacodec_1_1VideoReader.html',1,'cv::cudacodec']]],
  ['videowriter',['VideoWriter',['https://docs.opencv.org/3.4.1/df/dde/classcv_1_1cudacodec_1_1VideoWriter.html',1,'cv::cudacodec::VideoWriter'],['https://docs.opencv.org/3.4.1/dd/d9e/classcv_1_1VideoWriter.html',1,'cv::VideoWriter']]],
  ['viz3d',['Viz3d',['https://docs.opencv.org/3.4.1/d6/d32/classcv_1_1viz_1_1Viz3d.html',1,'cv::viz']]],
  ['voronoiseamfinder',['VoronoiSeamFinder',['https://docs.opencv.org/3.4.1/db/d24/classcv_1_1detail_1_1VoronoiSeamFinder.html',1,'cv::detail']]]
];
