var searchData=
[
  ['nano',['nano',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['nanoseconds',['nanoseconds',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['narymatiterator',['NAryMatIterator',['https://docs.opencv.org/3.4.1/d5/dd2/classcv_1_1NAryMatIterator.html',1,'cv']]],
  ['ncvbroxopticalflowdescriptor',['NCVBroxOpticalFlowDescriptor',['https://docs.opencv.org/3.4.1/db/d7a/structNCVBroxOpticalFlowDescriptor.html',1,'']]],
  ['ncvmatrix',['NCVMatrix',['https://docs.opencv.org/3.4.1/de/d26/classNCVMatrix.html',1,'']]],
  ['ncvmatrixalloc',['NCVMatrixAlloc',['https://docs.opencv.org/3.4.1/d7/d3a/classNCVMatrixAlloc.html',1,'']]],
  ['ncvmatrixreuse',['NCVMatrixReuse',['https://docs.opencv.org/3.4.1/df/d82/classNCVMatrixReuse.html',1,'']]],
  ['ncvmemnativeallocator',['NCVMemNativeAllocator',['https://docs.opencv.org/3.4.1/dc/d18/classNCVMemNativeAllocator.html',1,'']]],
  ['ncvmemptr',['NCVMemPtr',['https://docs.opencv.org/3.4.1/d6/d86/structNCVMemPtr.html',1,'']]],
  ['ncvmemsegment',['NCVMemSegment',['https://docs.opencv.org/3.4.1/d2/d12/structNCVMemSegment.html',1,'']]],
  ['ncvmemstackallocator',['NCVMemStackAllocator',['https://docs.opencv.org/3.4.1/db/d74/classNCVMemStackAllocator.html',1,'']]],
  ['ncvpoint2d32s',['NcvPoint2D32s',['https://docs.opencv.org/3.4.1/d5/d93/structNcvPoint2D32s.html',1,'']]],
  ['ncvpoint2d32u',['NcvPoint2D32u',['https://docs.opencv.org/3.4.1/dc/d16/structNcvPoint2D32u.html',1,'']]],
  ['ncvrect32s',['NcvRect32s',['https://docs.opencv.org/3.4.1/d3/dfe/structNcvRect32s.html',1,'']]],
  ['ncvrect32u',['NcvRect32u',['https://docs.opencv.org/3.4.1/d0/d62/structNcvRect32u.html',1,'']]],
  ['ncvrect8u',['NcvRect8u',['https://docs.opencv.org/3.4.1/da/d3f/structNcvRect8u.html',1,'']]],
  ['ncvsize32s',['NcvSize32s',['https://docs.opencv.org/3.4.1/d7/dda/structNcvSize32s.html',1,'']]],
  ['ncvsize32u',['NcvSize32u',['https://docs.opencv.org/3.4.1/d8/dde/structNcvSize32u.html',1,'']]],
  ['ncvvector',['NCVVector',['https://docs.opencv.org/3.4.1/dc/d73/classNCVVector.html',1,'']]],
  ['ncvvectoralloc',['NCVVectorAlloc',['https://docs.opencv.org/3.4.1/d8/da0/classNCVVectorAlloc.html',1,'']]],
  ['ncvvectorreuse',['NCVVectorReuse',['https://docs.opencv.org/3.4.1/da/d61/classNCVVectorReuse.html',1,'']]],
  ['nearestinterptr',['NearestInterPtr',['https://docs.opencv.org/3.4.1/d0/df5/structcv_1_1cudev_1_1NearestInterPtr.html',1,'cv::cudev']]],
  ['nearestinterptrsz',['NearestInterPtrSz',['https://docs.opencv.org/3.4.1/df/dd0/structcv_1_1cudev_1_1NearestInterPtrSz.html',1,'cv::cudev']]],
  ['negate',['negate',['http://en.cppreference.com/w/cpp/utility/functional/negate.html',1,'std::negate'],['https://docs.opencv.org/3.4.1/d9/d77/structcv_1_1cudev_1_1negate.html',1,'cv::cudev::negate&lt; class &gt;']]],
  ['negative_5fbinomial_5fdistribution',['negative_binomial_distribution',['http://en.cppreference.com/w/cpp/numeric/random/negative_binomial_distribution.html',1,'std']]],
  ['nested_5fexception',['nested_exception',['http://en.cppreference.com/w/cpp/error/nested_exception.html',1,'std']]],
  ['net',['Net',['https://docs.opencv.org/3.4.1/db/d30/classcv_1_1dnn_1_1Net.html',1,'cv::dnn']]],
  ['new_5fhandler',['new_handler',['http://en.cppreference.com/w/cpp/memory/new/new_handler.html',1,'std']]],
  ['nnindex',['NNIndex',['https://docs.opencv.org/3.4.1/d9/d10/classcvflann_1_1NNIndex.html',1,'cvflann']]],
  ['nnindex_3c_20cv_3a_3al1_3c_20elementtype_20_3e_20_3e',['NNIndex&lt; cv::L1&lt; ElementType &gt; &gt;',['https://docs.opencv.org/3.4.1/d9/d10/classcvflann_1_1NNIndex.html',1,'']]],
  ['nnindex_3c_20cv_3a_3al2_3c_20elementtype_20_3e_20_3e',['NNIndex&lt; cv::L2&lt; ElementType &gt; &gt;',['https://docs.opencv.org/3.4.1/d9/d10/classcvflann_1_1NNIndex.html',1,'']]],
  ['no',['No',['https://docs.opencv.org/3.4.1/dc/d5a/structcv_1_1cudev_1_1IsUnaryFunction_1_1No.html',1,'cv::cudev::IsUnaryFunction&lt; class &gt;::No'],['https://docs.opencv.org/3.4.1/db/d13/structcv_1_1cudev_1_1IsBinaryFunction_1_1No.html',1,'cv::cudev::IsBinaryFunction&lt; class &gt;::No']]],
  ['nobundleadjuster',['NoBundleAdjuster',['https://docs.opencv.org/3.4.1/db/dd4/classcv_1_1detail_1_1NoBundleAdjuster.html',1,'cv::detail']]],
  ['node',['Node',['https://docs.opencv.org/3.4.1/d9/de0/structcv_1_1SparseMat_1_1Node.html',1,'cv::SparseMat::Node'],['https://docs.opencv.org/3.4.1/d2/d7d/structcv_1_1optflow_1_1GPCTree_1_1Node.html',1,'cv::optflow::GPCTree::Node'],['https://docs.opencv.org/3.4.1/d3/de3/classcv_1_1Node.html',1,'cv::Node&lt; OBJECT &gt;'],['https://docs.opencv.org/3.4.1/d4/d7d/classcv_1_1ml_1_1DTrees_1_1Node.html',1,'cv::ml::DTrees::Node']]],
  ['nodedata',['NodeData',['https://docs.opencv.org/3.4.1/d7/dc2/classcv_1_1instr_1_1NodeData.html',1,'cv::instr']]],
  ['nodedatatls',['NodeDataTls',['https://docs.opencv.org/3.4.1/da/df1/structcv_1_1instr_1_1NodeDataTls.html',1,'cv::instr']]],
  ['noexposurecompensator',['NoExposureCompensator',['https://docs.opencv.org/3.4.1/d2/dc1/classcv_1_1detail_1_1NoExposureCompensator.html',1,'cv::detail']]],
  ['normal_5fdistribution',['normal_distribution',['http://en.cppreference.com/w/cpp/numeric/random/normal_distribution.html',1,'std']]],
  ['normalbayesclassifier',['NormalBayesClassifier',['https://docs.opencv.org/3.4.1/d4/d8e/classcv_1_1ml_1_1NormalBayesClassifier.html',1,'cv::ml']]],
  ['normalizebboxlayer',['NormalizeBBoxLayer',['https://docs.opencv.org/3.4.1/dc/df8/classcv_1_1dnn_1_1NormalizeBBoxLayer.html',1,'cv::dnn']]],
  ['normhamming',['NormHamming',['https://docs.opencv.org/3.4.1/d5/d7b/structcv_1_1cudev_1_1NormHamming.html',1,'cv::cudev']]],
  ['normhistogramcostextractor',['NormHistogramCostExtractor',['https://docs.opencv.org/3.4.1/df/d65/classcv_1_1NormHistogramCostExtractor.html',1,'cv']]],
  ['norml1',['NormL1',['https://docs.opencv.org/3.4.1/d7/df8/structcv_1_1cudev_1_1NormL1.html',1,'cv::cudev']]],
  ['norml1_3c_20float_20_3e',['NormL1&lt; float &gt;',['https://docs.opencv.org/3.4.1/d5/d1e/structcv_1_1cudev_1_1NormL1_3_01float_01_4.html',1,'cv::cudev']]],
  ['norml2',['NormL2',['https://docs.opencv.org/3.4.1/dc/da6/structcv_1_1cudev_1_1NormL2.html',1,'cv::cudev']]],
  ['noseamfinder',['NoSeamFinder',['https://docs.opencv.org/3.4.1/d3/da9/classcv_1_1detail_1_1NoSeamFinder.html',1,'cv::detail']]],
  ['not_5fequal_5fto',['not_equal_to',['https://docs.opencv.org/3.4.1/df/d9f/structcv_1_1cudev_1_1not__equal__to.html',1,'cv::cudev::not_equal_to&lt; T &gt;'],['http://en.cppreference.com/w/cpp/utility/functional/not_equal_to.html',1,'std::not_equal_to']]],
  ['nothrow_5ft',['nothrow_t',['http://en.cppreference.com/w/cpp/memory/new/nothrow_t.html',1,'std']]],
  ['nppstinterpolationstate',['NppStInterpolationState',['https://docs.opencv.org/3.4.1/da/da9/structNppStInterpolationState.html',1,'']]],
  ['nsobject',['NSObject',['https://docs.opencv.org/3.4.1/d4/d19/classNSObject.html',1,'']]],
  ['nsobject_2dp_2dp',['NSObject-p-p',['https://docs.opencv.org/3.4.1/d9/d15/classNSObject-p.html',1,'']]],
  ['nsobjectnsobject_2dp_2dp',['NSObjectNSObject-p-p',['https://docs.opencv.org/3.4.1/d5/d25/classNSObjectNSObject-p.html',1,'']]],
  ['nulldeblurer',['NullDeblurer',['https://docs.opencv.org/3.4.1/dc/d86/classcv_1_1videostab_1_1NullDeblurer.html',1,'cv::videostab']]],
  ['nullframesource',['NullFrameSource',['https://docs.opencv.org/3.4.1/dd/d5b/classcv_1_1videostab_1_1NullFrameSource.html',1,'cv::videostab']]],
  ['nullinpainter',['NullInpainter',['https://docs.opencv.org/3.4.1/d4/d1d/classcv_1_1videostab_1_1NullInpainter.html',1,'cv::videostab']]],
  ['nulllog',['NullLog',['https://docs.opencv.org/3.4.1/d6/d78/classcv_1_1videostab_1_1NullLog.html',1,'cv::videostab']]],
  ['nulloutlierrejector',['NullOutlierRejector',['https://docs.opencv.org/3.4.1/d3/de9/classcv_1_1videostab_1_1NullOutlierRejector.html',1,'cv::videostab']]],
  ['nullptr_5ft',['nullptr_t',['http://en.cppreference.com/w/cpp/types/nullptr_t.html',1,'std']]],
  ['nulltype',['NullType',['https://docs.opencv.org/3.4.1/d5/d71/structcv_1_1cudev_1_1NullType.html',1,'cv::cudev']]],
  ['nullwobblesuppressor',['NullWobbleSuppressor',['https://docs.opencv.org/3.4.1/d0/da4/classcv_1_1videostab_1_1NullWobbleSuppressor.html',1,'cv::videostab']]],
  ['num_5fget',['num_get',['http://en.cppreference.com/w/cpp/locale/num_get.html',1,'std']]],
  ['num_5fput',['num_put',['http://en.cppreference.com/w/cpp/locale/num_put.html',1,'std']]],
  ['numeric_5flimits',['numeric_limits',['https://docs.opencv.org/3.4.1/db/dc8/structcv_1_1cudev_1_1numeric__limits.html',1,'cv::cudev::numeric_limits&lt; class &gt;'],['http://en.cppreference.com/w/cpp/types/numeric_limits.html',1,'std::numeric_limits']]],
  ['numeric_5flimits_3c_20bool_20_3e',['numeric_limits&lt; bool &gt;',['https://docs.opencv.org/3.4.1/da/d81/structcv_1_1cudev_1_1numeric__limits_3_01bool_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20double_20_3e',['numeric_limits&lt; double &gt;',['https://docs.opencv.org/3.4.1/d2/d80/structcv_1_1cudev_1_1numeric__limits_3_01double_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20float_20_3e',['numeric_limits&lt; float &gt;',['https://docs.opencv.org/3.4.1/db/d88/structcv_1_1cudev_1_1numeric__limits_3_01float_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20schar_20_3e',['numeric_limits&lt; schar &gt;',['https://docs.opencv.org/3.4.1/da/d4e/structcv_1_1cudev_1_1numeric__limits_3_01schar_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20short_20_3e',['numeric_limits&lt; short &gt;',['https://docs.opencv.org/3.4.1/d1/d8b/structcv_1_1cudev_1_1numeric__limits_3_01short_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20uchar_20_3e',['numeric_limits&lt; uchar &gt;',['https://docs.opencv.org/3.4.1/d3/dc7/structcv_1_1cudev_1_1numeric__limits_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20uint_20_3e',['numeric_limits&lt; uint &gt;',['https://docs.opencv.org/3.4.1/dd/d89/structcv_1_1cudev_1_1numeric__limits_3_01uint_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20ushort_20_3e',['numeric_limits&lt; ushort &gt;',['https://docs.opencv.org/3.4.1/df/d47/structcv_1_1cudev_1_1numeric__limits_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['numpunct',['numpunct',['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std']]],
  ['numpunct_5fbyname',['numpunct_byname',['http://en.cppreference.com/w/cpp/locale/numpunct_byname.html',1,'std']]]
];
