var searchData=
[
  ['icp_2ehpp',['icp.hpp',['https://docs.opencv.org/3.4.1/d3/d94/icp_8hpp.html',1,'']]],
  ['illuminationchange_2ecpp',['illuminationChange.cpp',['../illumination_change_8cpp.html',1,'']]],
  ['image_5fmanipulation_2emarkdown',['image_manipulation.markdown',['https://docs.opencv.org/3.4.1/d6/dd9/image__manipulation_8markdown.html',1,'']]],
  ['imdecode_2ecpp',['imdecode.cpp',['../imdecode_8cpp.html',1,'']]],
  ['imencode_2ecpp',['imencode.cpp',['../imencode_8cpp.html',1,'']]],
  ['img_5fhash_2ehpp',['img_hash.hpp',['https://docs.opencv.org/3.4.1/d4/d59/img__hash_8hpp.html',1,'']]],
  ['img_5fhash_5fbase_2ehpp',['img_hash_base.hpp',['https://docs.opencv.org/3.4.1/d9/db6/img__hash__base_8hpp.html',1,'']]],
  ['imgcodecs_2ehpp',['imgcodecs.hpp',['https://docs.opencv.org/3.4.1/d7/dd8/imgcodecs_2imgcodecs_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/3.4.1/d6/d87/imgcodecs_8hpp.html',1,'(Global Namespace)']]],
  ['imgcodecs_5fc_2eh',['imgcodecs_c.h',['https://docs.opencv.org/3.4.1/d5/dd5/imgcodecs__c_8h.html',1,'']]],
  ['imghash_5f_2ecpp',['ImgHash_.cpp',['../_img_hash___8cpp.html',1,'']]],
  ['imgproc_2ehpp',['imgproc.hpp',['https://docs.opencv.org/3.4.1/d5/dba/imgproc_2imgproc_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/3.4.1/dd/d46/imgproc_8hpp.html',1,'(Global Namespace)']]],
  ['imgproc_5fc_2eh',['imgproc_c.h',['https://docs.opencv.org/3.4.1/d8/d85/imgproc__c_8h.html',1,'']]],
  ['imread_2ecpp',['imread.cpp',['../imread_8cpp.html',1,'']]],
  ['imreadmulti_2ecpp',['imreadmulti.cpp',['../imreadmulti_8cpp.html',1,'']]],
  ['imwrite_2ecpp',['imwrite.cpp',['../imwrite_8cpp.html',1,'']]],
  ['index_5ftesting_2eh',['index_testing.h',['https://docs.opencv.org/3.4.1/db/dd9/index__testing_8h.html',1,'']]],
  ['inferbbox_2ecpp',['InferBbox.cpp',['../_infer_bbox_8cpp.html',1,'']]],
  ['initcameramatrix2d_2ecpp',['initCameraMatrix2D.cpp',['../init_camera_matrix2_d_8cpp.html',1,'']]],
  ['initundistortrectifymap_2ecpp',['initUndistortRectifyMap.cpp',['../init_undistort_rectify_map_8cpp.html',1,'']]],
  ['initwideangleprojmap_2ecpp',['initWideAngleProjMap.cpp',['../init_wide_angle_proj_map_8cpp.html',1,'']]],
  ['inpaint_2ecpp',['inpaint.cpp',['../inpaint_8cpp.html',1,'']]],
  ['inpaint2_2ecpp',['inpaint2.cpp',['../inpaint2_8cpp.html',1,'']]],
  ['inpainting_2ehpp',['inpainting.hpp',['https://docs.opencv.org/3.4.1/d0/dae/modules_2videostab_2include_2opencv2_2videostab_2inpainting_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/3.4.1/de/da0/contrib_2modules_2xphoto_2include_2opencv2_2xphoto_2inpainting_8hpp.html',1,'(Global Namespace)']]],
  ['inpainting_2emarkdown',['inpainting.markdown',['https://docs.opencv.org/3.4.1/d0/d0f/inpainting_8markdown.html',1,'']]],
  ['inrange_2ecpp',['inRange.cpp',['../in_range_8cpp.html',1,'']]],
  ['install_5ftesseract_2emarkdown',['install_tesseract.markdown',['https://docs.opencv.org/3.4.1/de/d5b/install__tesseract_8markdown.html',1,'']]],
  ['integral_2ecpp',['integral.cpp',['../integral_8cpp.html',1,'']]],
  ['integral_2ehpp',['integral.hpp',['https://docs.opencv.org/3.4.1/d3/da8/integral_8hpp.html',1,'']]],
  ['intelperc_2emarkdown',['intelperc.markdown',['https://docs.opencv.org/3.4.1/d8/d80/intelperc_8markdown.html',1,'']]],
  ['interactive_5fcalibration_2emarkdown',['interactive_calibration.markdown',['https://docs.opencv.org/3.4.1/df/dc3/interactive__calibration_8markdown.html',1,'']]],
  ['interface_2eh',['interface.h',['https://docs.opencv.org/3.4.1/d2/d10/core_2include_2opencv2_2core_2hal_2interface_8h.html',1,'(Global Namespace)'],['https://docs.opencv.org/3.4.1/d5/d1e/imgproc_2include_2opencv2_2imgproc_2hal_2interface_8h.html',1,'(Global Namespace)'],['https://docs.opencv.org/3.4.1/d9/d0a/features2d_2include_2opencv2_2features2d_2hal_2interface_8h.html',1,'(Global Namespace)']]],
  ['interoperability_5fwith_5fopencv_5f1_2emarkdown',['interoperability_with_OpenCV_1.markdown',['https://docs.opencv.org/3.4.1/d4/dfd/interoperability__with__OpenCV__1_8markdown.html',1,'']]],
  ['interpolatecornerscharuco_2ecpp',['interpolateCornersCharuco.cpp',['../interpolate_corners_charuco_8cpp.html',1,'']]],
  ['interpolation_2ehpp',['interpolation.hpp',['https://docs.opencv.org/3.4.1/d8/d8e/interpolation_8hpp.html',1,'']]],
  ['intersectconvexconvex_2ecpp',['intersectConvexConvex.cpp',['../intersect_convex_convex_8cpp.html',1,'']]],
  ['intrin_2ehpp',['intrin.hpp',['https://docs.opencv.org/3.4.1/df/db4/intrin_8hpp.html',1,'']]],
  ['intrin_5fcpp_2ehpp',['intrin_cpp.hpp',['https://docs.opencv.org/3.4.1/d1/d94/intrin__cpp_8hpp.html',1,'']]],
  ['intrin_5fneon_2ehpp',['intrin_neon.hpp',['https://docs.opencv.org/3.4.1/dd/d52/intrin__neon_8hpp.html',1,'']]],
  ['intrin_5fsse_2ehpp',['intrin_sse.hpp',['https://docs.opencv.org/3.4.1/d2/d3c/intrin__sse_8hpp.html',1,'']]],
  ['intrin_5fvsx_2ehpp',['intrin_vsx.hpp',['https://docs.opencv.org/3.4.1/d3/d96/intrin__vsx_8hpp.html',1,'']]],
  ['intro_2emarkdown',['intro.markdown',['https://docs.opencv.org/3.4.1/d0/d2e/intro_8markdown.html',1,'']]],
  ['introduction_5fto_5fpca_2emarkdown',['introduction_to_pca.markdown',['https://docs.opencv.org/3.4.1/de/d8a/introduction__to__pca_8markdown.html',1,'']]],
  ['introduction_5fto_5fsvm_2emarkdown',['introduction_to_svm.markdown',['https://docs.opencv.org/3.4.1/d7/d6d/introduction__to__svm_8markdown.html',1,'']]],
  ['invert_2ecpp',['invert.cpp',['../invert_8cpp.html',1,'']]],
  ['invertaffinetransform_2ecpp',['invertAffineTransform.cpp',['../invert_affine_transform_8cpp.html',1,'']]],
  ['io_2ehpp',['io.hpp',['https://docs.opencv.org/3.4.1/d2/dc6/io_8hpp.html',1,'']]],
  ['ios_2eh',['ios.h',['https://docs.opencv.org/3.4.1/df/dd5/ios_8h.html',1,'']]],
  ['ios_5finstall_2emarkdown',['ios_install.markdown',['https://docs.opencv.org/3.4.1/d2/dc6/ios__install_8markdown.html',1,'']]],
  ['ippasync_2ehpp',['ippasync.hpp',['https://docs.opencv.org/3.4.1/d1/d8c/ippasync_8hpp.html',1,'']]],
  ['ir_5faffine_2ehpp',['ir_affine.hpp',['https://docs.opencv.org/3.4.1/d8/d32/ir__affine_8hpp.html',1,'']]],
  ['ir_5frobot_2ehpp',['ir_robot.hpp',['https://docs.opencv.org/3.4.1/d4/d5f/ir__robot_8hpp.html',1,'']]],
  ['is_5fbsds_2ehpp',['is_bsds.hpp',['https://docs.opencv.org/3.4.1/df/d12/is__bsds_8hpp.html',1,'']]],
  ['is_5fweizmann_2ehpp',['is_weizmann.hpp',['https://docs.opencv.org/3.4.1/d3/db5/is__weizmann_8hpp.html',1,'']]],
  ['iscontourconvex_2ecpp',['isContourConvex.cpp',['../is_contour_convex_8cpp.html',1,'']]]
];
