var searchData=
[
  ['hal_2ehpp',['hal.hpp',['https://docs.opencv.org/3.4.1/de/d0c/core_2include_2opencv2_2core_2hal_2hal_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/3.4.1/d4/d44/imgproc_2include_2opencv2_2imgproc_2hal_2hal_8hpp.html',1,'(Global Namespace)']]],
  ['hal_5freplacement_2ehpp',['hal_replacement.hpp',['https://docs.opencv.org/3.4.1/db/ddd/core_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/3.4.1/df/d91/imgproc_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/3.4.1/d2/dd9/features2d_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)']]],
  ['harris_5fdetector_2emarkdown',['harris_detector.markdown',['https://docs.opencv.org/3.4.1/db/d48/harris__detector_8markdown.html',1,'']]],
  ['harrislaplacefeaturedetector_5f_2ecpp',['HarrisLaplaceFeatureDetector_.cpp',['../_harris_laplace_feature_detector___8cpp.html',1,'']]],
  ['hausdorffdistanceextractor_5f_2ecpp',['HausdorffDistanceExtractor_.cpp',['../_hausdorff_distance_extractor___8cpp.html',1,'']]],
  ['hdf_2ehpp',['hdf.hpp',['https://docs.opencv.org/3.4.1/d7/d55/hdf_8hpp.html',1,'']]],
  ['hdf5_2eh',['hdf5.h',['https://docs.opencv.org/3.4.1/db/d87/hdf5_8h.html',1,'']]],
  ['hdf5_2ehpp',['hdf5.hpp',['https://docs.opencv.org/3.4.1/de/d24/hdf5_8hpp.html',1,'']]],
  ['hdr_5fimaging_2emarkdown',['hdr_imaging.markdown',['https://docs.opencv.org/3.4.1/d9/d87/hdr__imaging_8markdown.html',1,'']]],
  ['heap_2eh',['heap.h',['https://docs.opencv.org/3.4.1/da/ddb/heap_8h.html',1,'']]],
  ['hello_2emarkdown',['hello.markdown',['https://docs.opencv.org/3.4.1/da/da0/hello_8markdown.html',1,'']]],
  ['hfs_2ehpp',['hfs.hpp',['https://docs.opencv.org/3.4.1/de/d29/hfs_8hpp.html',1,'']]],
  ['hfssegment_5f_2ecpp',['HfsSegment_.cpp',['../_hfs_segment___8cpp.html',1,'']]],
  ['hierarchical_5fclustering_5findex_2eh',['hierarchical_clustering_index.h',['https://docs.opencv.org/3.4.1/de/d1d/hierarchical__clustering__index_8h.html',1,'']]],
  ['highgui_2ehpp',['highgui.hpp',['https://docs.opencv.org/3.4.1/d0/dce/highgui_2highgui_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/3.4.1/d4/dd5/highgui_8hpp.html',1,'(Global Namespace)']]],
  ['highgui_5fc_2eh',['highgui_c.h',['https://docs.opencv.org/3.4.1/d5/d59/highgui__c_8h.html',1,'']]],
  ['highgui_5fwinrt_2ehpp',['highgui_winrt.hpp',['https://docs.opencv.org/3.4.1/d9/d22/highgui__winrt_8hpp.html',1,'']]],
  ['hist_5fcost_2ehpp',['hist_cost.hpp',['https://docs.opencv.org/3.4.1/df/d08/hist__cost_8hpp.html',1,'']]],
  ['histo3d_2emarkdown',['histo3D.markdown',['https://docs.opencv.org/3.4.1/df/dd7/histo3D_8markdown.html',1,'']]],
  ['histogram_2ehpp',['histogram.hpp',['https://docs.opencv.org/3.4.1/d5/d6e/histogram_8hpp.html',1,'']]],
  ['histogram_5fcalculation_2emarkdown',['histogram_calculation.markdown',['https://docs.opencv.org/3.4.1/d2/d3a/histogram__calculation_8markdown.html',1,'']]],
  ['histogram_5fcomparison_2emarkdown',['histogram_comparison.markdown',['https://docs.opencv.org/3.4.1/de/d12/histogram__comparison_8markdown.html',1,'']]],
  ['histogram_5fequalization_2emarkdown',['histogram_equalization.markdown',['https://docs.opencv.org/3.4.1/db/de8/histogram__equalization_8markdown.html',1,'']]],
  ['histogramphaseunwrapping_2ehpp',['histogramphaseunwrapping.hpp',['https://docs.opencv.org/3.4.1/df/dce/histogramphaseunwrapping_8hpp.html',1,'']]],
  ['hitormiss_2emarkdown',['hitOrMiss.markdown',['https://docs.opencv.org/3.4.1/d2/dbf/hitOrMiss_8markdown.html',1,'']]],
  ['hogdescriptor_5f_2ecpp',['HOGDescriptor_.cpp',['../_h_o_g_descriptor___8cpp.html',1,'']]],
  ['homography_2emarkdown',['homography.markdown',['https://docs.opencv.org/3.4.1/d2/dc8/homography_8markdown.html',1,'']]],
  ['hough_5fcircle_2emarkdown',['hough_circle.markdown',['https://docs.opencv.org/3.4.1/d4/d67/hough__circle_8markdown.html',1,'']]],
  ['hough_5flines_2emarkdown',['hough_lines.markdown',['https://docs.opencv.org/3.4.1/da/d5a/hough__lines_8markdown.html',1,'']]],
  ['houghcircles_2ecpp',['HoughCircles.cpp',['../_hough_circles_8cpp.html',1,'']]],
  ['houghlines_2ecpp',['HoughLines.cpp',['../_hough_lines_8cpp.html',1,'']]],
  ['houghlinesp_2ecpp',['HoughLinesP.cpp',['../_hough_lines_p_8cpp.html',1,'']]],
  ['houghlinespointset_2ecpp',['HoughLinesPointSet.cpp',['../_hough_lines_point_set_8cpp.html',1,'']]],
  ['houghpoint2line_2ecpp',['HoughPoint2Line.cpp',['../_hough_point2_line_8cpp.html',1,'']]],
  ['how_5fto_5fcreate_5fgroups_2emarkdown',['how_to_create_groups.markdown',['https://docs.opencv.org/3.4.1/d7/d7b/how__to__create__groups_8markdown.html',1,'']]],
  ['how_5fto_5fscan_5fimages_2emarkdown',['how_to_scan_images.markdown',['https://docs.opencv.org/3.4.1/d5/d91/how__to__scan__images_8markdown.html',1,'']]],
  ['how_5fto_5fuse_5fippa_5fconversion_2emarkdown',['how_to_use_ippa_conversion.markdown',['https://docs.opencv.org/3.4.1/da/d1e/how__to__use__ippa__conversion_8markdown.html',1,'']]],
  ['how_5fto_5fuse_5fopencv_5fparallel_5ffor_5f_2emarkdown',['how_to_use_OpenCV_parallel_for_.markdown',['https://docs.opencv.org/3.4.1/d5/d45/how__to__use__OpenCV__parallel__for___8markdown.html',1,'']]],
  ['hpe_5fhumaneva_2ehpp',['hpe_humaneva.hpp',['https://docs.opencv.org/3.4.1/d8/da7/hpe__humaneva_8hpp.html',1,'']]],
  ['hpe_5fparse_2ehpp',['hpe_parse.hpp',['https://docs.opencv.org/3.4.1/da/da9/hpe__parse_8hpp.html',1,'']]],
  ['hull_2emarkdown',['hull.markdown',['https://docs.opencv.org/3.4.1/d0/dbd/hull_8markdown.html',1,'']]],
  ['humoments_2ecpp',['HuMoments.cpp',['../_hu_moments_8cpp.html',1,'']]]
];
