var searchData=
[
  ['xalloc',['xalloc',['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::fstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ios::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_fstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::iostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ios_base::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wistream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::stringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wifstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_istream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::strstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_stringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::istrstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wiostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_istringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ifstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::istringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::istream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ostrstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wfstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_iostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wstringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wistringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ifstream::xalloc()']]],
  ['xor8u',['xor8u',['https://docs.opencv.org/3.4.1/d3/ddd/group__core__hal__functions.html#gaf6b6b88b438cb9b1c2beaeb0b8582117',1,'cv::hal::xor8u()'],['https://docs.opencv.org/3.4.1/d3/ddd/group__core__hal__functions.html#gaf6b6b88b438cb9b1c2beaeb0b8582117',1,'xor8u()(Global Namespace)']]],
  ['xsgetn',['xsgetn',['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::basic_filebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::wstringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::stringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::wfilebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::wstreambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::strstreambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::basic_stringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::basic_streambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::filebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::streambuf::xsgetn()']]],
  ['xsputn',['xsputn',['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::basic_filebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::wstringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::stringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::wfilebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::wstreambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::strstreambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::basic_stringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::basic_streambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::filebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::streambuf::xsputn()']]],
  ['xyz4_5fto_5fbgr_5f',['XYZ4_to_BGR_',['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga1c1cb51248a36d95defb3acacf2bd17a',1,'cv::cudev::XYZ4_to_BGR_()'],['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga1c1cb51248a36d95defb3acacf2bd17a',1,'XYZ4_to_BGR_()(Global Namespace)']]],
  ['xyz4_5fto_5fbgra_5f',['XYZ4_to_BGRA_',['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga580c1912fbe874425bfd3fddd04f8b37',1,'cv::cudev::XYZ4_to_BGRA_()'],['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga580c1912fbe874425bfd3fddd04f8b37',1,'XYZ4_to_BGRA_()(Global Namespace)']]],
  ['xyz4_5fto_5frgb_5f',['XYZ4_to_RGB_',['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga469900fdf8f2df64eba632ca1f4f640f',1,'cv::cudev::XYZ4_to_RGB_()'],['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga469900fdf8f2df64eba632ca1f4f640f',1,'XYZ4_to_RGB_()(Global Namespace)']]],
  ['xyz4_5fto_5frgba_5f',['XYZ4_to_RGBA_',['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga006138e07c79497e14b7662ee559e5f4',1,'cv::cudev::XYZ4_to_RGBA_()'],['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga006138e07c79497e14b7662ee559e5f4',1,'XYZ4_to_RGBA_()(Global Namespace)']]],
  ['xyz_5fto_5fbgr_5f',['XYZ_to_BGR_',['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga08eeb984f1bc615edc95f2b943a2a953',1,'cv::cudev::XYZ_to_BGR_()'],['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga08eeb984f1bc615edc95f2b943a2a953',1,'XYZ_to_BGR_()(Global Namespace)']]],
  ['xyz_5fto_5fbgra_5f',['XYZ_to_BGRA_',['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#gafa59c3529d696bd40fc187ee23097721',1,'cv::cudev::XYZ_to_BGRA_()'],['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#gafa59c3529d696bd40fc187ee23097721',1,'XYZ_to_BGRA_()(Global Namespace)']]],
  ['xyz_5fto_5frgb_5f',['XYZ_to_RGB_',['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga5cbe5591e22b72d34adaceabd753996a',1,'cv::cudev::XYZ_to_RGB_()'],['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga5cbe5591e22b72d34adaceabd753996a',1,'XYZ_to_RGB_()(Global Namespace)']]],
  ['xyz_5fto_5frgba_5f',['XYZ_to_RGBA_',['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga05fab24122b05eb1e0b3d6bb2a4850dc',1,'cv::cudev::XYZ_to_RGBA_()'],['https://docs.opencv.org/3.4.1/df/dfc/group__cudev.html#ga05fab24122b05eb1e0b3d6bb2a4850dc',1,'XYZ_to_RGBA_()(Global Namespace)']]]
];
