var searchData=
[
  ['calib3d_3a_20camera_20calibration_20and_203d_20reconstruction',['calib3d: Camera Calibration and 3D Reconstruction',['../group__calib3d.html',1,'']]],
  ['c_20api',['C API',['https://docs.opencv.org/3.4.1/d5/db8/group__calib3d__c.html',1,'']]],
  ['ccalib_3a_20custom_20calibration_20pattern_20for_203d_20reconstruction',['ccalib: Custom Calibration Pattern for 3D Reconstruction',['../group__ccalib.html',1,'']]],
  ['cnn_5f3dobj_3a_203d_20object_20recognition_20and_20pose_20estimation_20api',['cnn_3dobj: 3D Object Recognition and Pose Estimation API',['../group__cnn__3dobj.html',1,'']]],
  ['conditioning',['Conditioning',['https://docs.opencv.org/3.4.1/da/d8b/group__conditioning.html',1,'']]],
  ['core_3a_20core_20functionality',['core: Core Functionality',['../group__core.html',1,'']]],
  ['c_20structures_20and_20operations',['C structures and operations',['https://docs.opencv.org/3.4.1/d2/df8/group__core__c.html',1,'']]],
  ['connections_20with_20c_2b_2b',['Connections with C++',['https://docs.opencv.org/3.4.1/d8/dd7/group__core__c__glue.html',1,'']]],
  ['clustering',['Clustering',['https://docs.opencv.org/3.4.1/d5/d38/group__core__cluster.html',1,'']]],
  ['cholesky_20matrix_20decomposition',['Cholesky matrix decomposition',['https://docs.opencv.org/3.4.1/d8/d0e/group__core__hal__interface__decomp__cholesky.html',1,'']]],
  ['channel_20merge',['Channel merge',['https://docs.opencv.org/3.4.1/df/d2e/group__core__hal__interface__merge.html',1,'']]],
  ['channel_20split',['Channel split',['https://docs.opencv.org/3.4.1/df/df2/group__core__hal__interface__split.html',1,'']]],
  ['core_5flogging',['Core_logging',['https://docs.opencv.org/3.4.1/d3/dcb/group__core__logging.html',1,'']]],
  ['core_5futils_5fvsx',['Core_utils_vsx',['https://docs.opencv.org/3.4.1/d3/d50/group__core__utils__vsx.html',1,'']]],
  ['cuda_2daccelerated_20computer_20vision',['CUDA-accelerated Computer Vision',['https://docs.opencv.org/3.4.1/d1/d1e/group__cuda.html',1,'']]],
  ['core_20operations_20on_20matrices',['Core Operations on Matrices',['https://docs.opencv.org/3.4.1/de/d09/group__cudaarithm__core.html',1,'']]],
  ['core_20part',['Core part',['https://docs.opencv.org/3.4.1/d7/d05/group__cudacore.html',1,'']]],
  ['color_20space_20processing',['Color space processing',['https://docs.opencv.org/3.4.1/db/d8c/group__cudaimgproc__color.html',1,'']]],
  ['cvv_3a_20gui_20for_20interactive_20visual_20debugging_20of_20computer_20vision_20programs',['cvv: GUI for Interactive Visual Debugging of Computer Vision Programs',['../group__cvv.html',1,'']]],
  ['clustering_20and_20search_20in_20multi_2ddimensional_20spaces',['Clustering and Search in Multi-Dimensional Spaces',['https://docs.opencv.org/3.4.1/dc/de5/group__flann.html',1,'']]],
  ['c_20api',['C API',['https://docs.opencv.org/3.4.1/d0/d28/group__highgui__c.html',1,'']]],
  ['c_20api',['C API',['https://docs.opencv.org/3.4.1/da/d0a/group__imgcodecs__c.html',1,'']]],
  ['c_20api',['C API',['https://docs.opencv.org/3.4.1/df/d4e/group__imgproc__c.html',1,'']]],
  ['colormaps_20in_20opencv',['ColorMaps in OpenCV',['https://docs.opencv.org/3.4.1/d3/d50/group__imgproc__colormap.html',1,'']]],
  ['c_20api',['C API',['https://docs.opencv.org/3.4.1/d9/d31/group__objdetect__c.html',1,'']]],
  ['c_20api',['C API',['https://docs.opencv.org/3.4.1/d3/d40/group__photo__c.html',1,'']]],
  ['c_20api',['C API',['https://docs.opencv.org/3.4.1/d3/d12/group__video__c.html',1,'']]],
  ['c_20api_20for_20video_20i_2fo',['C API for video I/O',['https://docs.opencv.org/3.4.1/dd/d01/group__videoio__c.html',1,'']]]
];
